[pytest]
bdd_features_base_dir = tests/features/
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
asyncio_mode = auto
addopts = -v --strict-markers --cov=causaganha --cov-report=html --cov-report=term-missing
norecursedirs = scripts
