/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Diário de Justiça Eletrônico Nacional e Plataforma de Editais
 * Última atualização em 29/05/2025.<br>- Atualizado informações sobre parâmetros do endpoint GET /comunicacao.<br>- incluído informações sobre o controle de taxa de requisições (ratelimit) do endpoint GET /comunicacao.
 * OpenAPI spec version: 1.0.3
 */
import * as zod from 'zod';

/**
 * Método de autenticação, para operações de inclusão e remoção de comunicações processuais. Método a ser utilizado pelos Tribunais.
 */
export const postApiV1LoginBody = zod.object({
  "login": zod.string(),
  "senha": zod.string()
})

export const postApiV1LoginResponse = zod.object({
  "user": zod.object({
  "id": zod.number().optional().describe('Id do usuário'),
  "nome": zod.string().optional(),
  "email": zod.string().optional(),
  "cpf": zod.string().optional()
}).optional(),
  "access_token": zod.string().optional().describe('Token de autenticação a ser utilizado nas próximas requisições')
})


/**
 * Método de consulta de comunicações.<br><br><b>Atenção: as seguintes consultas são limitadas em 10000 resultados:</b><br>- pesquisas com campos textuais ou OAB (texto, nome de advogado, OAB e nome de parte)<br>- pesquisas com 5 ou menos itensPorPagina<br>- pesquisas com data de início e data de fim diferentes<br>- pesquisas com número de processo.<br><br>A pesquisa deve conter pelo menos um dos seguintes parâmetros: siglaTribunal, texto, nomeParte, nomeAdvogado, numeroOab, numeroProcesso ou ser limitada a 5 itensPorPagina.<br><br>As consultas estão sujeitas a controle de taxa de requisições por IP que pode ser controlado com os seguintes cabeçalhos retornados:<br>- x-ratelimit-limit: janela de quantidade de requisições<br>- x-ratelimit-remaining: quantidade de requisições restantes na atual janela.<br>Ao receber um erro 429 orienta-se aguardar 1 minuto para retomar as requisições para evitar um loop de erros.<br>A utilização de múltiplos IPs por um mesmo cliente para contornar o controle da taxa de requisições é considerado uso abusivo e poderá resultar em bloqueios.
 */
export const getApiV1ComunicacaoQueryParams = zod.object({
  "numeroOab": zod.string().optional(),
  "ufOab": zod.string().optional(),
  "nomeAdvogado": zod.string().optional(),
  "nomeParte": zod.string().optional(),
  "numeroProcesso": zod.string().optional(),
  "dataDisponibilizacaoInicio": zod.string().optional().describe('Data inicial de disponibilização da comunicação no diário, no formato yyyy-mm-dd'),
  "dataDisponibilizacaoFim": zod.string().optional().describe('Data fim de disponibilização da comunicação no diário, no formato yyyy-mm-dd'),
  "siglaTribunal": zod.string().optional().describe('Sigla do Tribunal para filtrar as comunicações'),
  "numeroComunicacao": zod.number().optional().describe('Número de identificação da comunicação'),
  "pagina": zod.number().optional().describe('Número da página'),
  "itensPorPagina": zod.number().optional().describe('Número de itens por página para paginação (valores válidos: 5 e 100)'),
  "orgaoId": zod.number().optional().describe('Identificador interno do órgão requisitante'),
  "meio": zod.enum(['E', 'D']).optional().describe('\"E\" para Edital e \"D\" para Diário Eletrônico')
})

export const getApiV1ComunicacaoResponse = zod.object({
  "status": zod.string().optional().describe('Status da operação'),
  "message": zod.string().optional(),
  "count": zod.number().optional().describe('Quantidade de comunicações retornadas'),
  "items": zod.array(zod.object({
  "id": zod.number().optional().describe('Id da comunicação'),
  "data_disponibilizacao": zod.string().optional().describe('Data em que a comunicação foi disponibilizada'),
  "siglaTribunal": zod.string().optional(),
  "tipoComunicacao": zod.string().optional().describe('Citação, intimação, edital, pauta de julgamento, lista de distribuição ou ata de sessão'),
  "nomeOrgao": zod.string().optional(),
  "texto": zod.string().optional().describe('Teor da Comunicação'),
  "numero_processo": zod.string().optional(),
  "meio": zod.string().optional().describe('Plataforma de Editais ou Diário de Justiça Eletrônico'),
  "link": zod.string().optional().describe('Link para o inteiro teor da comunicação'),
  "tipoDocumento": zod.string().optional(),
  "nomeClasse": zod.string().optional().describe('Classe do processo'),
  "codigoClasse": zod.string().optional(),
  "numeroComunicacao": zod.number().optional().describe('Número de identificação da comunicação'),
  "ativo": zod.boolean().optional(),
  "hash": zod.string().optional(),
  "datadisponibilizacao": zod.string().optional(),
  "meiocompleto": zod.string().optional(),
  "numeroprocessocommascara": zod.string().optional(),
  "destinatarios": zod.array(zod.object({
  "nome": zod.string().optional(),
  "polo": zod.string().optional().describe('A para Ativo, P para Passivo, T para Terceiro interessado e D para Outros Destinatários'),
  "comunicacao_id": zod.number().optional()
})).optional(),
  "destinatarioadvogados": zod.array(zod.object({
  "id": zod.number().optional(),
  "comunicacao_id": zod.number().optional(),
  "advogado_id": zod.number().optional(),
  "created_at": zod.string().optional(),
  "updated_at": zod.string().optional(),
  "advogado": zod.object({
  "id": zod.number(),
  "nome": zod.string(),
  "numero_oab": zod.string(),
  "uf_oab": zod.string()
}).optional()
})).optional()
})).optional()
})


/**
 * Método de inserção de novas comunicações, a ser utilizado pelos Tribunais
 */
export const postApiV1ComunicacaoBody = zod.object({
  "codigo_classe": zod.string().describe('Código da classe, conforme o SGT'),
  "numero_processo": zod.string().describe('Número do processo, conforme a numeração única do CNJ. Somente números.'),
  "sigla_tribunal": zod.string(),
  "meio": zod.enum(['"E"', '"D"']).describe('\"E\" para Edital e \"D\" para Diário Eletrônico'),
  "link": zod.string().optional().describe('Link para o inteiro teor da comunicação'),
  "texto": zod.string().optional().describe('Teor da comunicação'),
  "tipo_documento": zod.string(),
  "orgao": zod.string().describe('Órgão gerador da comunicação'),
  "data_disponibilizacao": zod.string().describe('Data em que a comunicação será disponibilizada, no formato aaaa-mm-dd. Deverá ser maior que a data de hoje. Não será aceita comunicação disponibilizada em finais de semana.'),
  "tipo_comunicacao": zod.enum(['"C"', '"I"', '"E"', '"P"', '"L"', '"A"']).describe('\"C\" para Citação, \"E\" para Edital, \"I\" para Intimação, \"P\" para Pauta de julgamento, \"L\" para Lista de distribuição e \"A\" para Ata de sessão'),
  "destinatarios": zod.array(zod.object({
  "nome": zod.string().optional().describe('Nome da parte'),
  "cpf_cnpj": zod.string().optional().describe('CPF ou CNPJ da parte'),
  "polo": zod.enum(['"A"', '"P"']).optional().describe('\"A\" para polo Ativo, \"P\" para polo Passivo, \"T\" para Terceiro interessado e \"D\" para Outros Destinatários.')
})),
  "advogados": zod.array(zod.object({
  "nome": zod.string().optional(),
  "numero_oab": zod.string().optional(),
  "uf_oab": zod.string().optional()
})).optional()
})

export const postApiV1ComunicacaoResponse = zod.object({
  "status": zod.string().optional().describe('Status da operação'),
  "message": zod.string().optional(),
  "items": zod.array(zod.object({
  "tribunal_id": zod.number().optional().describe('Identificador interno do tribunal para a requisição'),
  "classe_id": zod.number().optional().describe('Identificador interno da classe processual para a requisição'),
  "tipo_documento_id": zod.number().optional().describe('Identificador interno do tipo de documento para a requisição'),
  "orgao_id": zod.number().optional().describe('Identificador interno do orgao requisitante'),
  "tipo_id": zod.number().optional().describe('Identificador interno do tipo da comunicação '),
  "id": zod.number().optional().describe('Id da comunicação'),
  "data_publicacao": zod.string().optional().describe('Data em que a comunicação foi disponibilizada, no formato yyyy-mm-dd'),
  "texto": zod.string().optional().describe('Teor da Comunicação'),
  "numero_processo": zod.string().optional(),
  "meio": zod.string().optional().describe('Plataforma de Editais ou Diário de Justiça Eletrônico'),
  "link": zod.string().optional().describe('Link para o inteiro teor da comunicação'),
  "numero_comunicacao": zod.number().optional().describe('Número de identificação da comunicação'),
  "ativo": zod.boolean().optional(),
  "hash": zod.string().optional(),
  "meiocompleto": zod.string().optional(),
  "numeroprocessocommascara": zod.string().optional(),
  "destinatarios": zod.array(zod.object({
  "nome": zod.string().optional(),
  "polo": zod.string().optional().describe('A para Ativo, P para Passivo, T para Terceiro interessado e D para Outros Destinatários'),
  "cpf_cnpj": zod.string().optional().describe('CPF ou CNPJ do destinatário'),
  "comunicacao_id": zod.number().optional()
})).optional(),
  "destinatarioadvogados": zod.array(zod.object({
  "id": zod.number().optional(),
  "comunicacao_id": zod.number().optional(),
  "advogado_id": zod.number().optional(),
  "created_at": zod.string().optional(),
  "updated_at": zod.string().optional(),
  "advogado": zod.object({
  "id": zod.number(),
  "nome": zod.string(),
  "numero_oab": zod.string(),
  "uf_oab": zod.string(),
  "tipo_inscricao": zod.string().optional(),
  "email": zod.string().optional()
}).optional()
})).optional()
})).optional()
})


/**
 * GET /api/v1/comunicacao/{hash}/certidao
 */
export const getApiV1ComunicacaoHashCertidaoParams = zod.object({
  "hash": zod.string()
})


/**
 * Este endpoint retorna lista de tribunais por UF de atuação com as datas de último envio disponibilizado pelo tribunal.
 */
export const getApiV1ComunicacaoTribunalResponseItem = zod.object({
  "id": zod.number().optional().describe('Identificador único do Tribunal'),
  "nome": zod.string().optional().describe('Nome completo do Tribunal'),
  "sigla": zod.string().optional().describe('Sigla do Tribunal'),
  "jurisdicao": zod.string().optional().describe('Descrição da jurisdição do Tribunal'),
  "endereco": zod.string().optional().describe('Endereço completo do Tribunal'),
  "telefone": zod.string().optional().describe('Telefone de contato do Tribunal')
})
export const getApiV1ComunicacaoTribunalResponse = zod.array(getApiV1ComunicacaoTribunalResponseItem)


/**
 * Cancela comunicações. Caso a comunicação não tenha sido disponibilizada, não aparecerá em qualquer forma nas consultas. Caso a comunicação já tenha sido disponibilizada, o conteúdo será substituído pelo motivo de cancelamento. Pode levar algumas horas para refletir em todas as pesquisas do sistema.
 */
export const deleteApiV1ComunicacaoIdParams = zod.object({
  "id": zod.string()
})

export const deleteApiV1ComunicacaoIdBody = zod.object({
  "motivo_cancelamento": zod.string()
})

export const deleteApiV1ComunicacaoIdResponse = zod.object({
  "status": zod.string().optional().describe('Indica status da requisição. Ex. success'),
  "message": zod.string().optional().describe('Mensagem de confirmação.')
})


/**
 * Método para download dos cadernos compactados de comunicações de cada tribunal.<br>O endpoint retorna metadados sobre o caderno e URL temporária (5 minutos) para download.<br>Os cadernos do dia atual são disponibilizados a partir das 02:00.
 */
export const getApiV1CadernoSiglaTribunalDataMeioParams = zod.object({
  "sigla_tribunal": zod.string(),
  "data": zod.iso.date(),
  "meio": zod.enum(['E', 'D']).describe('\"E\" para Edital e \"D\" para Diário Eletrônico')
})

export const getApiV1CadernoSiglaTribunalDataMeioResponse = zod.object({
  "tribunal": zod.string().optional().describe('Nome completo do tribunal'),
  "sigla_tribunal": zod.string().optional().describe('Sigla do tribunal'),
  "meio": zod.string().optional().describe('D ou E'),
  "status": zod.string().optional().describe('Status do processamento. Não Processado, Em processamento, Processado, Sem comunicações ou Cancelado.'),
  "versao": zod.string().optional().describe('Número da versão do diário. A versão é incrementada quando o diário precisa ser reprocessado, como no caso de cancelamento de comunicações.'),
  "data": zod.string().optional().describe('Data referência no formado YYYY-MM-DD'),
  "total_comunicacoes": zod.number().optional().describe('Número de comunicações'),
  "numero_paginas": zod.number().optional().describe('Número de arquivos dentro do pacote compactado'),
  "hash": zod.string().optional().describe('Hash SHA256 do arquivo'),
  "url": zod.string().optional().describe('URL temporária de download')
})
