/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Método de autenticação, para operações de inclusão e remoção de comunicações processuais. Método a ser utilizado pelos Tribunais. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Login do usuário cadastrado no sistema de controle de acesso do CNJ (SCA) */
            requestBody?: {
                content: {
                    "application/json": {
                        login: string;
                        senha: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            user?: {
                                /** @description Id do usuário */
                                id?: number;
                                nome?: string;
                                email?: string;
                                cpf?: string;
                            };
                            /** @description Token de autenticação a ser utilizado nas próximas requisições */
                            access_token?: string;
                        };
                    };
                };
                /** @description Credenciais inválidas */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Erro negocial */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/comunicacao": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Método de consulta de comunicações.<br><br><b>Atenção: as seguintes consultas são limitadas em 10000 resultados:</b><br>- pesquisas com campos textuais ou OAB (texto, nome de advogado, OAB e nome de parte)<br>- pesquisas com 5 ou menos itensPorPagina<br>- pesquisas com data de início e data de fim diferentes<br>- pesquisas com número de processo.<br><br>A pesquisa deve conter pelo menos um dos seguintes parâmetros: siglaTribunal, texto, nomeParte, nomeAdvogado, numeroOab, numeroProcesso ou ser limitada a 5 itensPorPagina.<br><br>As consultas estão sujeitas a controle de taxa de requisições por IP que pode ser controlado com os seguintes cabeçalhos retornados:<br>- x-ratelimit-limit: janela de quantidade de requisições<br>- x-ratelimit-remaining: quantidade de requisições restantes na atual janela.<br>Ao receber um erro 429 orienta-se aguardar 1 minuto para retomar as requisições para evitar um loop de erros.<br>A utilização de múltiplos IPs por um mesmo cliente para contornar o controle da taxa de requisições é considerado uso abusivo e poderá resultar em bloqueios. */
        get: {
            parameters: {
                query?: {
                    numeroOab?: string;
                    ufOab?: string;
                    nomeAdvogado?: string;
                    nomeParte?: string;
                    numeroProcesso?: string;
                    /** @description Data inicial de disponibilização da comunicação no diário, no formato yyyy-mm-dd */
                    dataDisponibilizacaoInicio?: string;
                    /** @description Data fim de disponibilização da comunicação no diário, no formato yyyy-mm-dd */
                    dataDisponibilizacaoFim?: string;
                    /** @description Sigla do Tribunal para filtrar as comunicações */
                    siglaTribunal?: string;
                    /** @description Número de identificação da comunicação */
                    numeroComunicacao?: number;
                    /** @description Número da página */
                    pagina?: number;
                    /** @description Número de itens por página para paginação (valores válidos: 5 e 100) */
                    itensPorPagina?: number;
                    /** @description Identificador interno do órgão requisitante */
                    orgaoId?: number;
                    /** @description "E" para Edital e "D" para Diário Eletrônico */
                    meio?: "E" | "D";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description Status da operação */
                            status?: string;
                            message?: string;
                            /** @description Quantidade de comunicações retornadas */
                            count?: number;
                            items?: {
                                /** @description Id da comunicação */
                                id?: number;
                                /** @description Data em que a comunicação foi disponibilizada */
                                data_disponibilizacao?: string;
                                siglaTribunal?: string;
                                /** @description Citação, intimação, edital, pauta de julgamento, lista de distribuição ou ata de sessão */
                                tipoComunicacao?: string;
                                nomeOrgao?: string;
                                /** @description Teor da Comunicação */
                                texto?: string;
                                numero_processo?: string;
                                /** @description Plataforma de Editais ou Diário de Justiça Eletrônico */
                                meio?: string;
                                /** @description Link para o inteiro teor da comunicação */
                                link?: string;
                                tipoDocumento?: string;
                                /** @description Classe do processo */
                                nomeClasse?: string;
                                codigoClasse?: string;
                                /** @description Número de identificação da comunicação */
                                numeroComunicacao?: number;
                                ativo?: boolean;
                                hash?: string;
                                datadisponibilizacao?: string;
                                meiocompleto?: string;
                                numeroprocessocommascara?: string;
                                destinatarios?: {
                                    nome?: string;
                                    /** @description A para Ativo, P para Passivo, T para Terceiro interessado e D para Outros Destinatários */
                                    polo?: string;
                                    comunicacao_id?: number;
                                }[];
                                destinatarioadvogados?: {
                                    id?: number;
                                    comunicacao_id?: number;
                                    advogado_id?: number;
                                    created_at?: string;
                                    updated_at?: string;
                                    advogado?: {
                                        id: number;
                                        nome: string;
                                        numero_oab: string;
                                        uf_oab: string;
                                    };
                                }[];
                            }[];
                        };
                    };
                };
                /** @description Erro negocial */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Erro por taxa de requisições elevado */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /** @description Método de inserção de novas comunicações, a ser utilizado pelos Tribunais */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /** @description Código da classe, conforme o SGT */
                        codigo_classe: string;
                        /** @description Número do processo, conforme a numeração única do CNJ. Somente números. */
                        numero_processo: string;
                        sigla_tribunal: string;
                        /**
                         * @description "E" para Edital e "D" para Diário Eletrônico
                         * @enum {string}
                         */
                        meio: "\"E\"" | "\"D\"";
                        /** @description Link para o inteiro teor da comunicação */
                        link?: string;
                        /** @description Teor da comunicação */
                        texto?: string;
                        tipo_documento: string;
                        /** @description Órgão gerador da comunicação */
                        orgao: string;
                        /** @description Data em que a comunicação será disponibilizada, no formato aaaa-mm-dd. Deverá ser maior que a data de hoje. Não será aceita comunicação disponibilizada em finais de semana. */
                        data_disponibilizacao: string;
                        /**
                         * @description "C" para Citação, "E" para Edital, "I" para Intimação, "P" para Pauta de julgamento, "L" para Lista de distribuição e "A" para Ata de sessão
                         * @enum {string}
                         */
                        tipo_comunicacao: "\"C\"" | "\"I\"" | "\"E\"" | "\"P\"" | "\"L\"" | "\"A\"";
                        destinatarios: {
                            /** @description Nome da parte */
                            nome?: string;
                            /** @description CPF ou CNPJ da parte */
                            cpf_cnpj?: string;
                            /**
                             * @description "A" para polo Ativo, "P" para polo Passivo, "T" para Terceiro interessado e "D" para Outros Destinatários.
                             * @enum {string}
                             */
                            polo?: "\"A\"" | "\"P\"";
                        }[];
                        advogados?: {
                            nome?: string;
                            numero_oab?: string;
                            uf_oab?: string;
                        }[];
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description Status da operação */
                            status?: string;
                            message?: string;
                            items?: {
                                /** @description Identificador interno do tribunal para a requisição */
                                tribunal_id?: number;
                                /** @description Identificador interno da classe processual para a requisição */
                                classe_id?: number;
                                /** @description Identificador interno do tipo de documento para a requisição */
                                tipo_documento_id?: number;
                                /** @description Identificador interno do orgao requisitante */
                                orgao_id?: number;
                                /** @description Identificador interno do tipo da comunicação */
                                tipo_id?: number;
                                /** @description Id da comunicação */
                                id?: number;
                                /** @description Data em que a comunicação foi disponibilizada, no formato yyyy-mm-dd */
                                data_publicacao?: string;
                                /** @description Teor da Comunicação */
                                texto?: string;
                                numero_processo?: string;
                                /** @description Plataforma de Editais ou Diário de Justiça Eletrônico */
                                meio?: string;
                                /** @description Link para o inteiro teor da comunicação */
                                link?: string;
                                /** @description Número de identificação da comunicação */
                                numero_comunicacao?: number;
                                ativo?: boolean;
                                hash?: string;
                                meiocompleto?: string;
                                numeroprocessocommascara?: string;
                                destinatarios?: {
                                    nome?: string;
                                    /** @description A para Ativo, P para Passivo, T para Terceiro interessado e D para Outros Destinatários */
                                    polo?: string;
                                    /** @description CPF ou CNPJ do destinatário */
                                    cpf_cnpj?: string;
                                    comunicacao_id?: number;
                                }[];
                                destinatarioadvogados?: {
                                    id?: number;
                                    comunicacao_id?: number;
                                    advogado_id?: number;
                                    created_at?: string;
                                    updated_at?: string;
                                    advogado?: {
                                        id: number;
                                        nome: string;
                                        numero_oab: string;
                                        uf_oab: string;
                                        tipo_inscricao?: string;
                                        email?: string;
                                    };
                                }[];
                            }[];
                        };
                    };
                };
                /** @description Erro negocial */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/comunicacao/{hash}/certidao": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description GET /api/v1/comunicacao/{hash}/certidao */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    hash: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/comunicacao/tribunal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Este endpoint retorna lista de tribunais por UF de atuação com as datas de último envio disponibilizado pelo tribunal. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Sucesso ao retornar as informações dos Tribunais */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description Identificador único do Tribunal */
                            id?: number;
                            /** @description Nome completo do Tribunal */
                            nome?: string;
                            /** @description Sigla do Tribunal */
                            sigla?: string;
                            /** @description Descrição da jurisdição do Tribunal */
                            jurisdicao?: string;
                            /** @description Endereço completo do Tribunal */
                            endereco?: string;
                            /** @description Telefone de contato do Tribunal */
                            telefone?: string;
                        }[];
                    };
                };
                /** @description Nenhum Tribunal encontrado */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example error */
                            status?: string;
                            /** @example Nenhum Tribunal encontrado. */
                            message?: string;
                        };
                    };
                };
                /** @description Erro interno no servidor */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example error */
                            status?: string;
                            /** @example Erro interno ao buscar as informações dos Tribunais. */
                            message?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/comunicacao/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** @description Cancela comunicações. Caso a comunicação não tenha sido disponibilizada, não aparecerá em qualquer forma nas consultas. Caso a comunicação já tenha sido disponibilizada, o conteúdo será substituído pelo motivo de cancelamento. Pode levar algumas horas para refletir em todas as pesquisas do sistema. */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            /** @description Request body opcional caso a comunicação seja cancelada antes da disponibilização e obrigatória após a disponibilização. */
            requestBody?: {
                content: {
                    "application/json": {
                        motivo_cancelamento: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description Indica status da requisição. Ex. success */
                            status?: string;
                            /** @description Mensagem de confirmação. */
                            message?: string;
                        };
                    };
                };
                /** @description Credenciais inválidas */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Erro negocial */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/caderno/{sigla_tribunal}/{data}/{meio}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Método para download dos cadernos compactados de comunicações de cada tribunal.<br>O endpoint retorna metadados sobre o caderno e URL temporária (5 minutos) para download.<br>Os cadernos do dia atual são disponibilizados a partir das 02:00. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    sigla_tribunal: string;
                    data: string;
                    /** @description "E" para Edital e "D" para Diário Eletrônico */
                    meio: "E" | "D";
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description Nome completo do tribunal */
                            tribunal?: string;
                            /** @description Sigla do tribunal */
                            sigla_tribunal?: string;
                            /** @description D ou E */
                            meio?: string;
                            /** @description Status do processamento. Não Processado, Em processamento, Processado, Sem comunicações ou Cancelado. */
                            status?: string;
                            /** @description Número da versão do diário. A versão é incrementada quando o diário precisa ser reprocessado, como no caso de cancelamento de comunicações. */
                            versao?: string;
                            /** @description Data referência no formado YYYY-MM-DD */
                            data?: string;
                            /** @description Número de comunicações */
                            total_comunicacoes?: number;
                            /** @description Número de arquivos dentro do pacote compactado */
                            numero_paginas?: number;
                            /** @description Hash SHA256 do arquivo */
                            hash?: string;
                            /** @description URL temporária de download */
                            url?: string;
                        };
                    };
                };
                /** @description Erro negocial */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
