// GENERATED by scripts/generate_okf_zod_schemas.py — do not edit by hand.
// Regenerate: uv run python scripts/generate_okf_zod_schemas.py
// Generated by okf-parser
import { z } from 'zod';

export const DatajudCapaSchema = z.object({
  "assuntos": z.string(),
  "classe_oficial": z.string(),
  "data_ajuizamento": z.string(),
  "description": z.string().optional(),
  "grau": z.string(),
  "id": z.string(),
  "orgao_julgador": z.string(),
  "title": z.string().optional(),
  "type": z.literal("DatajudCapa"),
  "ultima_atualizacao": z.string()
});

export const DjenResumoSchema = z.object({
  "description": z.string().optional(),
  "id": z.string(),
  "n_publicacoes": z.union([z.number().int(), z.bigint()]),
  "primeira_publicacao": z.string(),
  "title": z.string().optional(),
  "tribunais": z.array(z.string()),
  "type": z.literal("DjenResumo"),
  "ultima_publicacao": z.string()
});

export const DocumentoProcessoSchema = z.object({
  "data": z.string(),
  "description": z.string().optional(),
  "fonte": z.string(),
  "id_documento": z.string(),
  "processo_nr": z.string().describe("references Processo(nr_processo)"),
  "resumo": z.string(),
  "tipo": z.string(),
  "title": z.string().optional(),
  "type": z.literal("DocumentoProcesso"),
  "url": z.string()
});

export const FonteSchema = z.object({
  "acesso": z.string(),
  "description": z.string().optional(),
  "natureza": z.string(),
  "nome": z.string(),
  "oficial": z.boolean(),
  "orgao": z.string(),
  "title": z.string().optional(),
  "type": z.literal("Fonte")
});

export const FonteCoberturaSchema = z.object({
  "description": z.string().optional(),
  "fonte": z.string(),
  "id": z.string(),
  "processo_nr": z.string().describe("references Processo(nr_processo)"),
  "registros": z.union([z.number().int(), z.bigint()]),
  "status": z.string(),
  "title": z.string().optional(),
  "type": z.literal("FonteCobertura")
});

export const JurisDecisaoSchema = z.object({
  "classe": z.string(),
  "data_julgamento": z.string(),
  "description": z.string().optional(),
  "id": z.string(),
  "n_documentos": z.union([z.number().int(), z.bigint()]),
  "orgao": z.string(),
  "relator": z.string(),
  "tipos": z.array(z.string()),
  "title": z.string().optional(),
  "type": z.literal("JurisDecisao"),
  "url": z.string()
});

export const PipelineSchema = z.object({
  "cadencia_cron": z.string(),
  "canario_semantica": z.string(),
  "description": z.string().optional(),
  "fonte": z.string().describe("references Fonte(nome)"),
  "mcp_status": z.string(),
  "modo": z.string(),
  "nome": z.string(),
  "pacote": z.string(),
  "publicacao_semantica": z.string(),
  "saida_canonica": z.string(),
  "sucesso_semantica": z.string(),
  "tentativa_semantica": z.string(),
  "title": z.string().optional(),
  "type": z.literal("Pipeline"),
  "workflow": z.string()
});

export const ProcessoSchema = z.object({
  "avisos": z.array(z.string()),
  "datajud_id": z.string().describe("references DatajudCapa(id)"),
  "dataset_gerado_em": z.string(),
  "description": z.string().optional(),
  "djen_id": z.string().describe("references DjenResumo(id)"),
  "documentos_truncados": z.boolean(),
  "encontrado": z.boolean(),
  "fontes_presentes": z.array(z.string()),
  "juris_id": z.string().describe("references JurisDecisao(id)"),
  "nr_processo": z.string(),
  "nr_processo_mascara": z.string(),
  "stj_id": z.string().describe("references StjAcordao(id)"),
  "title": z.string().optional(),
  "type": z.literal("Processo")
});

export const StjAcordaoSchema = z.object({
  "classe": z.string(),
  "data_decisao": z.string(),
  "data_publicacao": z.string(),
  "description": z.string().optional(),
  "ementa": z.string(),
  "id": z.string(),
  "relator": z.string(),
  "tema": z.string(),
  "tese": z.string(),
  "title": z.string().optional(),
  "type": z.literal("StjAcordao")
});

export const ProcessoConsultarSchema = z.object({
  "avisos": z.array(z.string()),
  "datajud_id": z.string().describe("references DatajudCapa(id)"),
  "dataset_gerado_em": z.string(),
  "description": z.string().optional(),
  "djen_id": z.string().describe("references DjenResumo(id)"),
  "documentos_truncados": z.boolean(),
  "encontrado": z.boolean(),
  "fontes_presentes": z.array(z.string()),
  "juris_id": z.string().describe("references JurisDecisao(id)"),
  "nr_processo": z.string(),
  "nr_processo_mascara": z.string(),
  "stj_id": z.string().describe("references StjAcordao(id)"),
  "title": z.string().optional(),
  "type": z.literal("Processo"),
  "djen": DjenResumoSchema.nullable(),
  "juris": JurisDecisaoSchema.nullable(),
  "stj": StjAcordaoSchema.nullable(),
  "datajud": DatajudCapaSchema.nullable(),
  "cobertura_dataset": z.array(FonteCoberturaSchema),
  "documentos": z.array(DocumentoProcessoSchema)
});
