// GENERATED by scripts/generate_okf_zod_schemas.py — do not edit by hand.
// Regenerate: uv run python scripts/generate_okf_zod_schemas.py
// Generated by okf-parser
import { z } from 'zod';

export const AgentCheckSchema = z.object({
  "command": z.string(),
  "description": z.string().optional(),
  "evidence_id": z.string().describe("references AgentEvidence(id)"),
  "goal_id": z.string().describe("references AgentGoal(id)"),
  "id": z.string(),
  "result": z.string(),
  "run_id": z.string().describe("references AgentRun(id)"),
  "summary": z.string(),
  "title": z.string().optional(),
  "type": z.literal("AgentCheck")
});

export const AgentDecisionSchema = z.object({
  "choice": z.string(),
  "description": z.string().optional(),
  "goal_id": z.string().describe("references AgentGoal(id)"),
  "id": z.string(),
  "question": z.string(),
  "rationale": z.string(),
  "run_id": z.string().describe("references AgentRun(id)"),
  "title": z.string().optional(),
  "type": z.literal("AgentDecision")
});

export const AgentEvidenceSchema = z.object({
  "description": z.string().optional(),
  "goal_id": z.string().describe("references AgentGoal(id)"),
  "id": z.string(),
  "kind": z.string(),
  "reference": z.string(),
  "run_id": z.string().describe("references AgentRun(id)"),
  "summary": z.string(),
  "title": z.string().optional(),
  "type": z.literal("AgentEvidence")
});

export const AgentGoalSchema = z.object({
  "description": z.string().optional(),
  "goal": z.string(),
  "id": z.string(),
  "rationale": z.string(),
  "run_id": z.string().describe("references AgentRun(id)"),
  "status": z.string(),
  "success_signal": z.string(),
  "title": z.string().optional(),
  "type": z.literal("AgentGoal")
});

export const AgentReadingSchema = z.object({
  "description": z.string().optional(),
  "finding": z.string(),
  "id": z.string(),
  "reference": z.string(),
  "run_id": z.string().describe("references AgentRun(id)"),
  "subject": z.string(),
  "title": z.string().optional(),
  "type": z.literal("AgentReading")
});

export const AgentRunSchema = z.object({
  "branch_at_start": z.string(),
  "check_ids": z.array(z.string()),
  "claude_md_reading_id": z.string(),
  "commit_at_start": z.string(),
  "completed_at": z.string(),
  "considered_work": z.array(z.string()),
  "decision_ids": z.array(z.string()),
  "description": z.string().optional(),
  "entry_state": z.string(),
  "evidence_ids": z.array(z.string()),
  "expected_behavior": z.string(),
  "goal_ids": z.array(z.string()),
  "id": z.string(),
  "issues_reading_id": z.string(),
  "next_move": z.string(),
  "okf_reading_id": z.string(),
  "primary_goal_id": z.string(),
  "prs_reading_id": z.string(),
  "result_state": z.string(),
  "result_summary": z.string(),
  "selected_work": z.string(),
  "started_at": z.string(),
  "target_state": z.string(),
  "title": z.string().optional(),
  "type": z.literal("AgentRun")
});

export const DatajudCapaSchema = z.object({
  "assuntos": z.string().nullable(),
  "classe_oficial": z.string().nullable(),
  "data_ajuizamento": z.string().nullable(),
  "description": z.string().optional(),
  "grau": z.string().nullable(),
  "id": z.string(),
  "orgao_julgador": z.string().nullable(),
  "title": z.string().optional(),
  "type": z.literal("DatajudCapa"),
  "ultima_atualizacao": z.string().nullable()
});

export const DjenResumoSchema = z.object({
  "description": z.string().optional(),
  "id": z.string(),
  "n_publicacoes": z.union([z.number().int(), z.bigint()]).nullable(),
  "primeira_publicacao": z.string().nullable(),
  "title": z.string().optional(),
  "tribunais": z.array(z.string()),
  "type": z.literal("DjenResumo"),
  "ultima_publicacao": z.string().nullable()
});

export const DocumentoProcessoSchema = z.object({
  "data": z.string().nullable(),
  "description": z.string().optional(),
  "fonte": z.string(),
  "id_documento": z.string(),
  "processo_nr": z.string().describe("references Processo(nr_processo)"),
  "resumo": z.string().nullable(),
  "tipo": z.string().nullable(),
  "title": z.string().optional(),
  "type": z.literal("DocumentoProcesso"),
  "url": z.string().nullable()
});

export const FonteSchema = z.object({
  "acesso": z.string(),
  "description": z.string().optional(),
  "natureza": z.string(),
  "nome": z.string(),
  "oficial": z.boolean(),
  "orgao": z.string(),
  "title": z.string().optional(),
  "type": z.literal("Fonte")
});

export const FonteCoberturaSchema = z.object({
  "description": z.string().optional(),
  "fonte": z.string(),
  "id": z.string(),
  "processo_nr": z.string().describe("references Processo(nr_processo)"),
  "registros": z.union([z.number().int(), z.bigint()]),
  "status": z.string(),
  "title": z.string().optional(),
  "type": z.literal("FonteCobertura")
});

export const JurisDecisaoSchema = z.object({
  "classe": z.string().nullable(),
  "data_julgamento": z.string().nullable(),
  "description": z.string().optional(),
  "id": z.string(),
  "n_documentos": z.union([z.number().int(), z.bigint()]).nullable(),
  "orgao": z.string().nullable(),
  "relator": z.string().nullable(),
  "tipos": z.array(z.string()),
  "title": z.string().optional(),
  "type": z.literal("JurisDecisao"),
  "url": z.string().nullable()
});

export const PipelineSchema = z.object({
  "cadencia_cron": z.string(),
  "canario_semantica": z.string(),
  "description": z.string().optional(),
  "fonte": z.string().describe("references Fonte(nome)"),
  "mcp_status": z.string(),
  "modo": z.string(),
  "nome": z.string(),
  "pacote": z.string(),
  "publicacao_semantica": z.string(),
  "saida_canonica": z.string(),
  "sucesso_semantica": z.string(),
  "tentativa_semantica": z.string(),
  "title": z.string().optional(),
  "type": z.literal("Pipeline"),
  "workflow": z.string()
});

export const ProcessoSchema = z.object({
  "avisos": z.array(z.string()),
  "datajud_id": z.string().describe("references DatajudCapa(id)").nullable(),
  "dataset_gerado_em": z.string().nullable(),
  "description": z.string().optional(),
  "djen_id": z.string().describe("references DjenResumo(id)").nullable(),
  "documentos_truncados": z.boolean(),
  "encontrado": z.boolean(),
  "fontes_presentes": z.array(z.string()),
  "juris_id": z.string().describe("references JurisDecisao(id)").nullable(),
  "nr_processo": z.string(),
  "nr_processo_mascara": z.string(),
  "stj_id": z.string().describe("references StjAcordao(id)").nullable(),
  "title": z.string().optional(),
  "type": z.literal("Processo")
});

export const StjAcordaoSchema = z.object({
  "classe": z.string().nullable(),
  "data_decisao": z.string().nullable(),
  "data_publicacao": z.string().nullable(),
  "description": z.string().optional(),
  "ementa": z.string().nullable(),
  "id": z.string(),
  "relator": z.string().nullable(),
  "tema": z.string().nullable(),
  "tese": z.string().nullable(),
  "title": z.string().optional(),
  "type": z.literal("StjAcordao")
});

export const ProcessoConsultarSchema = z.object({
  "avisos": z.array(z.string()),
  "datajud_id": z.string().describe("references DatajudCapa(id)").nullable(),
  "dataset_gerado_em": z.string().nullable(),
  "description": z.string().optional(),
  "djen_id": z.string().describe("references DjenResumo(id)").nullable(),
  "documentos_truncados": z.boolean(),
  "encontrado": z.boolean(),
  "fontes_presentes": z.array(z.string()),
  "juris_id": z.string().describe("references JurisDecisao(id)").nullable(),
  "nr_processo": z.string(),
  "nr_processo_mascara": z.string(),
  "stj_id": z.string().describe("references StjAcordao(id)").nullable(),
  "title": z.string().optional(),
  "type": z.literal("Processo"),
  "djen": DjenResumoSchema.nullable(),
  "juris": JurisDecisaoSchema.nullable(),
  "stj": StjAcordaoSchema.nullable(),
  "datajud": DatajudCapaSchema.nullable(),
  "cobertura_dataset": z.array(FonteCoberturaSchema),
  "documentos": z.array(DocumentoProcessoSchema)
});
