"""Contract tests for the OKF-generated Zod schemas module (#1105 slice 3).

`web/src/lib/processoConsultar.gen.ts` must be produced mechanically by
`scripts/generate_okf_zod_schemas.py` from the same `knowledge/`
TypeContract bundle that already generates
`src/causaganha_mcp/_generated/domain_models.py` for the MCP surface
(`scripts/generate_okf_domain_models.py`, #1105 slice 2). Without this
module, the Web surface has no generated binding for `ProcessoConsultar`
and keeps redescribing the dossiê shape by hand in
`web/src/lib/processoCnj.ts`, which is exactly the drift #1105 exists to
remove.

These tests:

- catch drift between the checked-in generated file and what the current
  bundle would produce today (the same check CI runs before merge);
- prove the generated module actually declares a `ProcessoConsultarSchema`
  Zod schema that references the same per-source concept schemas the
  Pydantic binding uses (`DjenResumoSchema`, `JurisDecisaoSchema`,
  `StjAcordaoSchema`, `DatajudCapaSchema`), so MCP and Web validate one
  projection instead of two.
"""

from __future__ import annotations

import sys
from pathlib import Path


sys.path.insert(0, str(Path(__file__).resolve().parents[2] / "scripts"))
from generate_okf_zod_schemas import _OUTPUT_PATH, render  # noqa: E402


def test_generated_zod_schemas_file_matches_current_knowledge_bundle() -> None:
    """The checked-in generated file must be exactly what `knowledge/` produces today.

    Fails the same way CI's drift gate does when someone edits the bundle
    (or the generated file itself) without rerunning the generator.
    """
    assert _OUTPUT_PATH.read_text(encoding="utf-8") == render()


def test_generated_module_is_not_hand_edited() -> None:
    """The checked-in file must carry the do-not-edit-by-hand banner."""
    content = _OUTPUT_PATH.read_text(encoding="utf-8")
    assert "GENERATED by scripts/generate_okf_zod_schemas.py" in content
    assert "do not edit by hand" in content


def test_generated_module_declares_processo_consultar_schema() -> None:
    """The projection schema and the per-source schemas it composes must exist."""
    content = _OUTPUT_PATH.read_text(encoding="utf-8")
    assert "import { z } from 'zod';" in content
    assert "export const ProcessoConsultarSchema = z.object({" in content
    for name in (
        "DjenResumoSchema",
        "JurisDecisaoSchema",
        "StjAcordaoSchema",
        "DatajudCapaSchema",
        "FonteCoberturaSchema",
        "DocumentoProcessoSchema",
    ):
        assert f"export const {name} = z.object({{" in content, name


def test_processo_consultar_schema_composes_nullable_per_source_schemas() -> None:
    """A source with no record for a CNJ must be `nullable()`, not reinlined optional shape."""
    content = _OUTPUT_PATH.read_text(encoding="utf-8")
    projection_start = content.index("export const ProcessoConsultarSchema")
    projection_body = content[projection_start:]
    assert '"djen": DjenResumoSchema.nullable()' in projection_body
    assert '"juris": JurisDecisaoSchema.nullable()' in projection_body
    assert '"stj": StjAcordaoSchema.nullable()' in projection_body
    assert '"datajud": DatajudCapaSchema.nullable()' in projection_body
