# GENERATED by scripts/generate_okf_domain_models.py — do not edit by hand.
# Regenerate: uv run python scripts/generate_okf_domain_models.py
"""Generated Pydantic models from OKF schema contracts."""

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict, Field


class DatajudCapaConcept(BaseModel):
    """Generated Pydantic model for one OKF contract object."""

    model_config = ConfigDict(extra="allow")

    assuntos: str
    classe_oficial: str
    data_ajuizamento: str
    description: str = Field(default=None)
    grau: str
    id: str
    orgao_julgador: str
    title: str = Field(default=None)
    type: Literal["DatajudCapa"]
    ultima_atualizacao: str


class DjenResumoConcept(BaseModel):
    """Generated Pydantic model for one OKF contract object."""

    model_config = ConfigDict(extra="allow")

    description: str = Field(default=None)
    id: str
    n_publicacoes: str
    primeira_publicacao: str
    title: str = Field(default=None)
    tribunais: list[str]
    type: Literal["DjenResumo"]
    ultima_publicacao: str


class DocumentoProcessoConcept(BaseModel):
    """Generated Pydantic model for one OKF contract object."""

    model_config = ConfigDict(extra="allow")

    data: str
    description: str = Field(default=None)
    fonte: str
    id_documento: str
    processo_nr: str = Field(
        json_schema_extra={
            "x-okf-references": {
                "type": "Processo",
                "columns": ["processo_nr"],
                "referencedColumns": ["nr_processo"],
                "position": 0,
            },
        },
    )
    resumo: str
    tipo: str
    title: str = Field(default=None)
    type: Literal["DocumentoProcesso"]
    url: str


class FonteConcept(BaseModel):
    """Generated Pydantic model for one OKF contract object."""

    model_config = ConfigDict(extra="allow")

    acesso: str
    description: str = Field(default=None)
    natureza: str
    nome: str
    oficial: str
    orgao: str
    title: str = Field(default=None)
    type: Literal["Fonte"]


class FonteCoberturaConcept(BaseModel):
    """Generated Pydantic model for one OKF contract object."""

    model_config = ConfigDict(extra="allow")

    description: str = Field(default=None)
    fonte: str
    id: str
    processo_nr: str = Field(
        json_schema_extra={
            "x-okf-references": {
                "type": "Processo",
                "columns": ["processo_nr"],
                "referencedColumns": ["nr_processo"],
                "position": 0,
            },
        },
    )
    registros: str
    status: str
    title: str = Field(default=None)
    type: Literal["FonteCobertura"]


class JurisDecisaoConcept(BaseModel):
    """Generated Pydantic model for one OKF contract object."""

    model_config = ConfigDict(extra="allow")

    classe: str
    data_julgamento: str
    description: str = Field(default=None)
    id: str
    n_documentos: str
    orgao: str
    relator: str
    tipos: list[str]
    title: str = Field(default=None)
    type: Literal["JurisDecisao"]
    url: str


class PipelineConcept(BaseModel):
    """Generated Pydantic model for one OKF contract object."""

    model_config = ConfigDict(extra="allow")

    cadencia_cron: str
    canario_semantica: str
    description: str = Field(default=None)
    fonte: str = Field(
        json_schema_extra={
            "x-okf-references": {
                "type": "Fonte",
                "columns": ["fonte"],
                "referencedColumns": ["nome"],
                "position": 0,
            },
        },
    )
    mcp_status: str
    modo: str
    nome: str
    pacote: str
    publicacao_semantica: str
    saida_canonica: str
    sucesso_semantica: str
    tentativa_semantica: str
    title: str = Field(default=None)
    type: Literal["Pipeline"]
    workflow: str


class ProcessoConcept(BaseModel):
    """Generated Pydantic model for one OKF contract object."""

    model_config = ConfigDict(extra="allow")

    avisos: list[str]
    datajud_id: str = Field(
        json_schema_extra={
            "x-okf-references": {
                "type": "DatajudCapa",
                "columns": ["datajud_id"],
                "referencedColumns": ["id"],
                "position": 0,
            },
        },
    )
    dataset_gerado_em: str
    description: str = Field(default=None)
    djen_id: str = Field(
        json_schema_extra={
            "x-okf-references": {
                "type": "DjenResumo",
                "columns": ["djen_id"],
                "referencedColumns": ["id"],
                "position": 0,
            },
        },
    )
    documentos_truncados: str
    encontrado: str
    fontes_presentes: list[str]
    juris_id: str = Field(
        json_schema_extra={
            "x-okf-references": {
                "type": "JurisDecisao",
                "columns": ["juris_id"],
                "referencedColumns": ["id"],
                "position": 0,
            },
        },
    )
    nr_processo: str
    nr_processo_mascara: str
    stj_id: str = Field(
        json_schema_extra={
            "x-okf-references": {
                "type": "StjAcordao",
                "columns": ["stj_id"],
                "referencedColumns": ["id"],
                "position": 0,
            },
        },
    )
    title: str = Field(default=None)
    type: Literal["Processo"]


class StjAcordaoConcept(BaseModel):
    """Generated Pydantic model for one OKF contract object."""

    model_config = ConfigDict(extra="allow")

    classe: str
    data_decisao: str
    data_publicacao: str
    description: str = Field(default=None)
    ementa: str
    id: str
    relator: str
    tema: str
    tese: str
    title: str = Field(default=None)
    type: Literal["StjAcordao"]


class ProcessoConsultarProjection(BaseModel):
    """Generated Pydantic model for one OKF contract object."""

    model_config = ConfigDict(extra="allow")

    avisos: list[str]
    datajud_id: str = Field(
        json_schema_extra={
            "x-okf-references": {
                "type": "DatajudCapa",
                "columns": ["datajud_id"],
                "referencedColumns": ["id"],
                "position": 0,
            },
        },
    )
    dataset_gerado_em: str
    description: str = Field(default=None)
    djen_id: str = Field(
        json_schema_extra={
            "x-okf-references": {
                "type": "DjenResumo",
                "columns": ["djen_id"],
                "referencedColumns": ["id"],
                "position": 0,
            },
        },
    )
    documentos_truncados: str
    encontrado: str
    fontes_presentes: list[str]
    juris_id: str = Field(
        json_schema_extra={
            "x-okf-references": {
                "type": "JurisDecisao",
                "columns": ["juris_id"],
                "referencedColumns": ["id"],
                "position": 0,
            },
        },
    )
    nr_processo: str
    nr_processo_mascara: str
    stj_id: str = Field(
        json_schema_extra={
            "x-okf-references": {
                "type": "StjAcordao",
                "columns": ["stj_id"],
                "referencedColumns": ["id"],
                "position": 0,
            },
        },
    )
    title: str = Field(default=None)
    type: Literal["Processo"]
    djen: DjenResumoConcept | None = Field(
        json_schema_extra={
            "x-okf-references": {
                "type": "DjenResumo",
                "columns": ["djen_id"],
                "referencedColumns": ["id"],
                "position": 0,
            },
        },
    )
    juris: JurisDecisaoConcept | None = Field(
        json_schema_extra={
            "x-okf-references": {
                "type": "JurisDecisao",
                "columns": ["juris_id"],
                "referencedColumns": ["id"],
                "position": 0,
            },
        },
    )
    stj: StjAcordaoConcept | None = Field(
        json_schema_extra={
            "x-okf-references": {
                "type": "StjAcordao",
                "columns": ["stj_id"],
                "referencedColumns": ["id"],
                "position": 0,
            },
        },
    )
    datajud: DatajudCapaConcept | None = Field(
        json_schema_extra={
            "x-okf-references": {
                "type": "DatajudCapa",
                "columns": ["datajud_id"],
                "referencedColumns": ["id"],
                "position": 0,
            },
        },
    )
    cobertura_dataset: list[FonteCoberturaConcept]
    documentos: list[DocumentoProcessoConcept]


DatajudCapaConcept.model_rebuild()
DjenResumoConcept.model_rebuild()
DocumentoProcessoConcept.model_rebuild()
FonteCoberturaConcept.model_rebuild()
JurisDecisaoConcept.model_rebuild()
StjAcordaoConcept.model_rebuild()
