# GENERATED by scripts/generate_okf_domain_models.py — do not edit by hand.
# Regenerate: uv run python scripts/generate_okf_domain_models.py
"""Generated Pydantic models from OKF schema contracts."""

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict, Field


class DatajudCapaConcept(BaseModel):
    """Generated Pydantic model for one OKF contract object."""

    model_config = ConfigDict(extra="allow")

    assuntos: str | None
    classe_oficial: str | None
    data_ajuizamento: str | None
    description: str = Field(default=None)
    grau: str | None
    id: str
    orgao_julgador: str | None
    title: str = Field(default=None)
    type: Literal["DatajudCapa"]
    ultima_atualizacao: str | None


class DjenResumoConcept(BaseModel):
    """Generated Pydantic model for one OKF contract object."""

    model_config = ConfigDict(extra="allow")

    description: str = Field(default=None)
    id: str
    n_publicacoes: int | None
    primeira_publicacao: str | None
    title: str = Field(default=None)
    tribunais: list[str]
    type: Literal["DjenResumo"]
    ultima_publicacao: str | None


class DocumentoProcessoConcept(BaseModel):
    """Generated Pydantic model for one OKF contract object."""

    model_config = ConfigDict(extra="allow")

    data: str | None
    description: str = Field(default=None)
    fonte: str
    id_documento: str
    processo_nr: str = Field(
        json_schema_extra={
            "x-okf-references": {
                "type": "Processo",
                "columns": ["processo_nr"],
                "referencedColumns": ["nr_processo"],
                "position": 0,
            },
        },
    )
    resumo: str | None
    tipo: str | None
    title: str = Field(default=None)
    type: Literal["DocumentoProcesso"]
    url: str | None


class FonteConcept(BaseModel):
    """Generated Pydantic model for one OKF contract object."""

    model_config = ConfigDict(extra="allow")

    acesso: str
    description: str = Field(default=None)
    natureza: str
    nome: str
    oficial: bool
    orgao: str
    title: str = Field(default=None)
    type: Literal["Fonte"]


class FonteCoberturaConcept(BaseModel):
    """Generated Pydantic model for one OKF contract object."""

    model_config = ConfigDict(extra="allow")

    description: str = Field(default=None)
    fonte: str
    id: str
    processo_nr: str = Field(
        json_schema_extra={
            "x-okf-references": {
                "type": "Processo",
                "columns": ["processo_nr"],
                "referencedColumns": ["nr_processo"],
                "position": 0,
            },
        },
    )
    registros: int
    status: str
    title: str = Field(default=None)
    type: Literal["FonteCobertura"]


class JurisDecisaoConcept(BaseModel):
    """Generated Pydantic model for one OKF contract object."""

    model_config = ConfigDict(extra="allow")

    classe: str | None
    data_julgamento: str | None
    description: str = Field(default=None)
    id: str
    n_documentos: int | None
    orgao: str | None
    relator: str
    tipos: list[str]
    title: str = Field(default=None)
    type: Literal["JurisDecisao"]
    url: str | None


class PipelineConcept(BaseModel):
    """Generated Pydantic model for one OKF contract object."""

    model_config = ConfigDict(extra="allow")

    cadencia_cron: str
    canario_semantica: str
    description: str = Field(default=None)
    fonte: str = Field(
        json_schema_extra={
            "x-okf-references": {
                "type": "Fonte",
                "columns": ["fonte"],
                "referencedColumns": ["nome"],
                "position": 0,
            },
        },
    )
    mcp_status: str
    modo: str
    nome: str
    pacote: str
    publicacao_semantica: str
    saida_canonica: str
    sucesso_semantica: str
    tentativa_semantica: str
    title: str = Field(default=None)
    type: Literal["Pipeline"]
    workflow: str


class ProcessoConcept(BaseModel):
    """Generated Pydantic model for one OKF contract object."""

    model_config = ConfigDict(extra="allow")

    avisos: list[str]
    datajud_id: str | None = Field(
        json_schema_extra={
            "x-okf-references": {
                "type": "DatajudCapa",
                "columns": ["datajud_id"],
                "referencedColumns": ["id"],
                "position": 0,
            },
        },
    )
    dataset_gerado_em: str | None
    description: str = Field(default=None)
    djen_id: str | None = Field(
        json_schema_extra={
            "x-okf-references": {
                "type": "DjenResumo",
                "columns": ["djen_id"],
                "referencedColumns": ["id"],
                "position": 0,
            },
        },
    )
    documentos_truncados: bool
    encontrado: bool
    fontes_presentes: list[str]
    juris_id: str | None = Field(
        json_schema_extra={
            "x-okf-references": {
                "type": "JurisDecisao",
                "columns": ["juris_id"],
                "referencedColumns": ["id"],
                "position": 0,
            },
        },
    )
    nr_processo: str
    nr_processo_mascara: str
    stj_id: str | None = Field(
        json_schema_extra={
            "x-okf-references": {
                "type": "StjAcordao",
                "columns": ["stj_id"],
                "referencedColumns": ["id"],
                "position": 0,
            },
        },
    )
    title: str = Field(default=None)
    type: Literal["Processo"]


class StjAcordaoConcept(BaseModel):
    """Generated Pydantic model for one OKF contract object."""

    model_config = ConfigDict(extra="allow")

    classe: str
    data_decisao: str | None
    data_publicacao: str | None
    description: str = Field(default=None)
    ementa: str | None
    id: str
    relator: str | None
    tema: str | None
    tese: str | None
    title: str = Field(default=None)
    type: Literal["StjAcordao"]


class ProcessoConsultarProjection(BaseModel):
    """Generated Pydantic model for one OKF contract object."""

    model_config = ConfigDict(extra="allow")

    avisos: list[str]
    datajud_id: str | None = Field(
        json_schema_extra={
            "x-okf-references": {
                "type": "DatajudCapa",
                "columns": ["datajud_id"],
                "referencedColumns": ["id"],
                "position": 0,
            },
        },
    )
    dataset_gerado_em: str | None
    description: str = Field(default=None)
    djen_id: str | None = Field(
        json_schema_extra={
            "x-okf-references": {
                "type": "DjenResumo",
                "columns": ["djen_id"],
                "referencedColumns": ["id"],
                "position": 0,
            },
        },
    )
    documentos_truncados: bool
    encontrado: bool
    fontes_presentes: list[str]
    juris_id: str | None = Field(
        json_schema_extra={
            "x-okf-references": {
                "type": "JurisDecisao",
                "columns": ["juris_id"],
                "referencedColumns": ["id"],
                "position": 0,
            },
        },
    )
    nr_processo: str
    nr_processo_mascara: str
    stj_id: str | None = Field(
        json_schema_extra={
            "x-okf-references": {
                "type": "StjAcordao",
                "columns": ["stj_id"],
                "referencedColumns": ["id"],
                "position": 0,
            },
        },
    )
    title: str = Field(default=None)
    type: Literal["Processo"]
    djen: DjenResumoConcept | None = Field(
        json_schema_extra={
            "x-okf-references": {
                "type": "DjenResumo",
                "columns": ["djen_id"],
                "referencedColumns": ["id"],
                "position": 0,
            },
        },
    )
    juris: JurisDecisaoConcept | None = Field(
        json_schema_extra={
            "x-okf-references": {
                "type": "JurisDecisao",
                "columns": ["juris_id"],
                "referencedColumns": ["id"],
                "position": 0,
            },
        },
    )
    stj: StjAcordaoConcept | None = Field(
        json_schema_extra={
            "x-okf-references": {
                "type": "StjAcordao",
                "columns": ["stj_id"],
                "referencedColumns": ["id"],
                "position": 0,
            },
        },
    )
    datajud: DatajudCapaConcept | None = Field(
        json_schema_extra={
            "x-okf-references": {
                "type": "DatajudCapa",
                "columns": ["datajud_id"],
                "referencedColumns": ["id"],
                "position": 0,
            },
        },
    )
    cobertura_dataset: list[FonteCoberturaConcept]
    documentos: list[DocumentoProcessoConcept]


DatajudCapaConcept.model_rebuild()
DjenResumoConcept.model_rebuild()
DocumentoProcessoConcept.model_rebuild()
FonteCoberturaConcept.model_rebuild()
JurisDecisaoConcept.model_rebuild()
StjAcordaoConcept.model_rebuild()
