ITEM_ID_PARTS_MIN = 3

"""Local archive fallback and protocol for testing.

The ``ArchiveService`` protocol and ``LocalArchiveService`` are retained for
local testing and development.  Production uploads to Internet Archive use the
httpx-based ``scripts/pipeline/ia_s3.py`` module.
"""

import asyncio
import shutil
from datetime import UTC, date, datetime
from pathlib import Path
from typing import Any, Protocol

import anyio
import structlog

from causaganha.clients.constants import (
    IA_DEFAULT_COLLECTION,
    IA_DEFAULT_CREATOR,
    IA_DEFAULT_MEDIATYPE,
    IA_DEFAULT_SUBJECTS,
)
from causaganha.config import DATA_DIR


logger = structlog.get_logger()


class ArchiveService(Protocol):
    """Abstract interface for archiving PDFs (Internet Archive or local fallback)."""

    async def upload_file(
        self,
        file_path: Path,
        item_id: str,
        metadata: dict[str, Any] | None = None,
    ) -> str | None:
        """Upload a file to the archive."""
        ...

    async def check_item_exists(self, item_id: str) -> bool:
        """Check whether an item already exists in the archive."""
        ...

    def generate_metadata(self, intimation_data: dict[str, Any]) -> dict[str, Any]:
        """Generate archive metadata from intimation data."""
        ...


class LocalArchiveService:
    """Local filesystem archive fallback (no API keys required)."""

    def __init__(self, archive_root: Path | None = None) -> None:
        """Initialize local archive with optional root directory."""
        self.archive_root = archive_root or (DATA_DIR / "pdf_archive")
        self.archive_root.mkdir(parents=True, exist_ok=True)

    async def upload_file(
        self,
        file_path: Path,
        item_id: str,
        metadata: dict[str, Any] | None = None,
    ) -> str | None:
        """Upload a file to local filesystem archive."""
        if not await anyio.Path(file_path).exists():
            logger.error("file_not_found", path=str(file_path))
            return None

        # Determine destination directory
        dest_dir = self.archive_root / item_id

        # If metadata is present, try to organize hierarchically
        if metadata:
            # We look for specific keys or try to parse
            # The pipeline passes metadata generated by `generate_metadata` or modified.
            # In our test we pass 'date' and 'tribunal_code'.
            # IA metadata usually has 'date' (YYYY-MM-DD).

            # Try to extract date
            date_str = metadata.get("date")
            # Try to extract tribunal.
            # In generate_metadata we put it in title or subject.
            # But relying on parsing title is brittle.
            # Ideally we should pass tribunal explicitly or extract it from item_id if it follows convention.
            # item_id format: causaganha-{tribunal}-{id}

            tribunal = metadata.get("tribunal_code")
            if not tribunal:
                # Try to parse from item_id
                parts = item_id.split("-")
                if len(parts) >= ITEM_ID_PARTS_MIN and parts[0] == "causaganha":
                    tribunal = parts[1].upper()

            if date_str and tribunal:
                try:
                    # Parse YYYY and MM
                    d = date.fromisoformat(str(date_str))
                    year = str(d.year)
                    month = f"{d.month:02d}"

                    dest_dir = self.archive_root / tribunal / year / month / item_id
                except ValueError:
                    # Invalid date format, fallback to flat
                    pass

        dest_dir.mkdir(parents=True, exist_ok=True)
        dest_path = dest_dir / file_path.name

        await asyncio.to_thread(shutil.copy2, file_path, dest_path)
        logger.info("local_archive_saved", item_id=item_id, path=str(dest_path))
        return str(dest_path)

    async def check_item_exists(self, item_id: str) -> bool:
        """Check whether an item exists in local archive."""
        # Check flat path (backward compatibility); hierarchical lookup
        # would require date/tribunal metadata, so we fall back to False.
        return (self.archive_root / item_id).exists()

    def generate_metadata(self, intimation_data: dict[str, Any]) -> dict[str, Any]:
        """Generate archive metadata from intimation data for hierarchical storage."""
        processo = intimation_data.get("numero_processo", "unknown")
        tribunal = intimation_data.get("sigla_tribunal", "unknown")
        data_pub = intimation_data.get(
            "data_disponibilizacao", datetime.now(UTC).date().isoformat()
        )

        return {
            "collection": IA_DEFAULT_COLLECTION,
            "mediatype": IA_DEFAULT_MEDIATYPE,
            "title": f"{tribunal} - Processo {processo}",
            "creator": IA_DEFAULT_CREATOR,
            "subject": [*IA_DEFAULT_SUBJECTS, tribunal.lower()],
            "description": f"Intimação judicial do processo {processo}",
            "date": data_pub,
            # Extra hint for local storage
            "tribunal_code": tribunal,
        }
