CREATE TABLE "AgentRun" (
    id VARCHAR,
    started_at VARCHAR,
    completed_at VARCHAR,
    branch_at_start VARCHAR,
    commit_at_start VARCHAR,
    claude_md_reading_id VARCHAR,
    issues_reading_id VARCHAR,
    prs_reading_id VARCHAR,
    okf_reading_id VARCHAR,
    goal_ids VARCHAR[],
    primary_goal_id VARCHAR,
    considered_work VARCHAR[],
    selected_work VARCHAR,
    expected_behavior VARCHAR,
    entry_state VARCHAR,
    target_state VARCHAR,
    decision_ids VARCHAR[],
    evidence_ids VARCHAR[],
    check_ids VARCHAR[],
    result_state VARCHAR,
    result_summary VARCHAR,
    next_move VARCHAR
);
