CREATE TABLE "AgentRun" (
    id VARCHAR,
    started_at VARCHAR,
    completed_at VARCHAR,
    branch_at_start VARCHAR,
    commit_at_start VARCHAR,
    read_claude_md BOOLEAN,
    read_open_issues BOOLEAN,
    read_open_prs BOOLEAN,
    read_okf_knowledge BOOLEAN,
    goals VARCHAR[],
    goal_rationale VARCHAR,
    considered_work VARCHAR[],
    selected_work VARCHAR,
    expected_behavior VARCHAR,
    entry_state VARCHAR,
    target_state VARCHAR,
    actions VARCHAR[],
    evidence VARCHAR[],
    checks VARCHAR[],
    result_state VARCHAR,
    result_summary VARCHAR,
    next_move VARCHAR
);
