// Copyright 2026 franklinbaldocausaganha. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newComunicacaoListCmd(flags *rootFlags) *cobra.Command {
	var flagNumeroOab string
	var flagUfOab string
	var flagNomeAdvogado string
	var flagNomeParte string
	var flagNumeroProcesso string
	var flagDataDisponibilizacaoInicio string
	var flagDataDisponibilizacaoFim string
	var flagSiglaTribunal string
	var flagNumeroComunicacao float64
	var flagPagina float64
	var flagItensPorPagina float64
	var flagOrgaoId float64
	var flagMeio string

	cmd := &cobra.Command{
		Use:         "list",
		Short:       "Método de consulta de comunicações.<br><br><b>Atenção: as seguintes consultas são limitadas em 10000...",
		Example:     "  djen-pp-cli comunicacao list",
		Annotations: map[string]string{"pp:endpoint": "comunicacao.list", "pp:method": "GET", "pp:path": "/api/v1/comunicacao", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if cmd.Flags().Changed("meio") {
				allowedMeio := []string{"E", "D"}
				validMeio := false
				for _, v := range allowedMeio {
					if flagMeio == v {
						validMeio = true
						break
					}
				}
				if !validMeio {
					fmt.Fprintf(os.Stderr, "warning: --%s %q not in allowed set %v\n", "meio", flagMeio, allowedMeio)
				}
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/api/v1/comunicacao"
			params := map[string]string{}
			if flagNumeroOab != "" {
				params["numeroOab"] = fmt.Sprintf("%v", flagNumeroOab)
			}
			if flagUfOab != "" {
				params["ufOab"] = fmt.Sprintf("%v", flagUfOab)
			}
			if flagNomeAdvogado != "" {
				params["nomeAdvogado"] = fmt.Sprintf("%v", flagNomeAdvogado)
			}
			if flagNomeParte != "" {
				params["nomeParte"] = fmt.Sprintf("%v", flagNomeParte)
			}
			if flagNumeroProcesso != "" {
				params["numeroProcesso"] = fmt.Sprintf("%v", flagNumeroProcesso)
			}
			if flagDataDisponibilizacaoInicio != "" {
				params["dataDisponibilizacaoInicio"] = fmt.Sprintf("%v", flagDataDisponibilizacaoInicio)
			}
			if flagDataDisponibilizacaoFim != "" {
				params["dataDisponibilizacaoFim"] = fmt.Sprintf("%v", flagDataDisponibilizacaoFim)
			}
			if flagSiglaTribunal != "" {
				params["siglaTribunal"] = fmt.Sprintf("%v", flagSiglaTribunal)
			}
			if flagNumeroComunicacao != 0.0 {
				params["numeroComunicacao"] = fmt.Sprintf("%v", flagNumeroComunicacao)
			}
			if flagPagina != 0.0 {
				params["pagina"] = fmt.Sprintf("%v", flagPagina)
			}
			if flagItensPorPagina != 0.0 {
				params["itensPorPagina"] = fmt.Sprintf("%v", flagItensPorPagina)
			}
			if flagOrgaoId != 0.0 {
				params["orgaoId"] = fmt.Sprintf("%v", flagOrgaoId)
			}
			if flagMeio != "" {
				params["meio"] = fmt.Sprintf("%v", flagMeio)
			}
			data, prov, err := resolveRead(cmd.Context(), c, flags, "comunicacao", false, path, params, nil)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Print provenance to stderr for human-facing output
			{
				var countItems []json.RawMessage
				_ = json.Unmarshal(data, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested. Explicit format flags (--csv, --quiet,
			// --plain) opt out of the auto-JSON path so piped consumers that asked for
			// a non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagNumeroOab, "numero-oab", "", "Numero oab")
	cmd.Flags().StringVar(&flagUfOab, "uf-oab", "", "Uf oab")
	cmd.Flags().StringVar(&flagNomeAdvogado, "nome-advogado", "", "Nome advogado")
	cmd.Flags().StringVar(&flagNomeParte, "nome-parte", "", "Nome parte")
	cmd.Flags().StringVar(&flagNumeroProcesso, "numero-processo", "", "Numero processo")
	cmd.Flags().StringVar(&flagDataDisponibilizacaoInicio, "data-disponibilizacao-inicio", "", "Data inicial de disponibilização da comunicação no diário, no formato yyyy-mm-dd")
	cmd.Flags().StringVar(&flagDataDisponibilizacaoFim, "data-disponibilizacao-fim", "", "Data fim de disponibilização da comunicação no diário, no formato yyyy-mm-dd")
	cmd.Flags().StringVar(&flagSiglaTribunal, "sigla-tribunal", "", "Sigla do Tribunal para filtrar as comunicações")
	cmd.Flags().Float64Var(&flagNumeroComunicacao, "numero-comunicacao", 0.0, "Número de identificação da comunicação")
	cmd.Flags().Float64Var(&flagPagina, "pagina", 0.0, "Número da página")
	cmd.Flags().Float64Var(&flagItensPorPagina, "itens-por-pagina", 0.0, "Número de itens por página para paginação (valores válidos: 5 e 100)")
	cmd.Flags().Float64Var(&flagOrgaoId, "orgao-id", 0.0, "Identificador interno do órgão requisitante")
	cmd.Flags().StringVar(&flagMeio, "meio", "", "'E' para Edital e 'D' para Diário Eletrônico (one of: E, D)")

	return cmd
}
