// Copyright 2026 franklinbaldocausaganha. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newComunicacaoCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "comunicacao",
		Short:  "Manage comunicacao",
		Hidden: true,
	}

	cmd.AddCommand(newComunicacaoCreateCmd(flags))
	cmd.AddCommand(newComunicacaoDeleteCmd(flags))
	cmd.AddCommand(newComunicacaoListCmd(flags))
	cmd.AddCommand(newComunicacaoListTribunalCmd(flags))
	cmd.AddCommand(newComunicacaoCertidaoCmd(flags))
	return cmd
}
