// Copyright 2026 franklinbaldocausaganha. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newComunicacaoCertidaoCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "certidao",
		Short: "Manage certidao",
	}

	cmd.AddCommand(newComunicacaoCertidaoGetCmd(flags))
	return cmd
}
