// Copyright 2026 franklinbaldocausaganha. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"
)

func newComunicacaoCreateCmd(flags *rootFlags) *cobra.Command {
	var bodyAdvogados string
	var bodyCodigoClasse string
	var bodyDataDisponibilizacao string
	var bodyDestinatarios string
	var bodyLink string
	var bodyMeio string
	var bodyNumeroProcesso string
	var bodyOrgao string
	var bodySiglaTribunal string
	var bodyTexto string
	var bodyTipoComunicacao string
	var bodyTipoDocumento string
	var stdinBody bool

	cmd := &cobra.Command{
		Use:         "create",
		Short:       "Método de inserção de novas comunicações, a ser utilizado pelos Tribunais",
		Example:     "  djen-pp-cli comunicacao create --codigo-classe example-value",
		Annotations: map[string]string{"pp:endpoint": "comunicacao.create", "pp:method": "POST", "pp:path": "/api/v1/comunicacao"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if !stdinBody {
				if !cmd.Flags().Changed("codigo-classe") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "codigo-classe")
				}
				if !cmd.Flags().Changed("data-disponibilizacao") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "data-disponibilizacao")
				}
				if !cmd.Flags().Changed("destinatarios") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "destinatarios")
				}
				if !cmd.Flags().Changed("meio") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "meio")
				}
				if !cmd.Flags().Changed("numero-processo") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "numero-processo")
				}
				if !cmd.Flags().Changed("orgao") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "orgao")
				}
				if !cmd.Flags().Changed("sigla-tribunal") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "sigla-tribunal")
				}
				if !cmd.Flags().Changed("tipo-comunicacao") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "tipo-comunicacao")
				}
				if !cmd.Flags().Changed("tipo-documento") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "tipo-documento")
				}
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/api/v1/comunicacao"
			var body map[string]any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				body = map[string]any{}
				if bodyAdvogados != "" {
					var parsedAdvogados any
					if err := json.Unmarshal([]byte(bodyAdvogados), &parsedAdvogados); err != nil {
						return fmt.Errorf("parsing --advogados JSON: %w", err)
					}
					body["advogados"] = parsedAdvogados
				}
				if bodyCodigoClasse != "" {
					body["codigo_classe"] = bodyCodigoClasse
				}
				if bodyDataDisponibilizacao != "" {
					body["data_disponibilizacao"] = bodyDataDisponibilizacao
				}
				if bodyDestinatarios != "" {
					var parsedDestinatarios any
					if err := json.Unmarshal([]byte(bodyDestinatarios), &parsedDestinatarios); err != nil {
						return fmt.Errorf("parsing --destinatarios JSON: %w", err)
					}
					body["destinatarios"] = parsedDestinatarios
				}
				if bodyLink != "" {
					body["link"] = bodyLink
				}
				if bodyMeio != "" {
					body["meio"] = bodyMeio
				}
				if bodyNumeroProcesso != "" {
					body["numero_processo"] = bodyNumeroProcesso
				}
				if bodyOrgao != "" {
					body["orgao"] = bodyOrgao
				}
				if bodySiglaTribunal != "" {
					body["sigla_tribunal"] = bodySiglaTribunal
				}
				if bodyTexto != "" {
					body["texto"] = bodyTexto
				}
				if bodyTipoComunicacao != "" {
					body["tipo_comunicacao"] = bodyTipoComunicacao
				}
				if bodyTipoDocumento != "" {
					body["tipo_documento"] = bodyTipoDocumento
				}
			}
			data, statusCode, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						return nil
					}
				} else {
					var wrapped struct {
						Data []map[string]any `json:"data"`
					}
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							return nil
						}
					}
				}
			}
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				if flags.quiet {
					return nil
				}
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				envelope := map[string]any{
					"action":   "post",
					"resource": "comunicacao",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300,
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						envelope["data"] = parsed
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				return printOutput(cmd.OutOrStdout(), json.RawMessage(envelopeJSON), true)
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&bodyAdvogados, "advogados", "", "Advogados")
	cmd.Flags().StringVar(&bodyCodigoClasse, "codigo-classe", "", "Código da classe, conforme o SGT")
	cmd.Flags().StringVar(&bodyDataDisponibilizacao, "data-disponibilizacao", "", "Data em que a comunicação será disponibilizada, no formato aaaa-mm-dd. Deverá ser maior que a data de hoje. Não...")
	cmd.Flags().StringVar(&bodyDestinatarios, "destinatarios", "", "Destinatarios")
	cmd.Flags().StringVar(&bodyLink, "link", "", "Link para o inteiro teor da comunicação")
	cmd.Flags().StringVar(&bodyMeio, "meio", "", "'E' para Edital e 'D' para Diário Eletrônico")
	cmd.Flags().StringVar(&bodyNumeroProcesso, "numero-processo", "", "Número do processo, conforme a numeração única do CNJ. Somente números.")
	cmd.Flags().StringVar(&bodyOrgao, "orgao", "", "Órgão gerador da comunicação")
	cmd.Flags().StringVar(&bodySiglaTribunal, "sigla-tribunal", "", "Sigla tribunal")
	cmd.Flags().StringVar(&bodyTexto, "texto", "", "Teor da comunicação")
	cmd.Flags().StringVar(&bodyTipoComunicacao, "tipo-comunicacao", "", "'C' para Citação, 'E' para Edital, 'I' para Intimação, 'P' para Pauta de julgamento, 'L' para Lista de...")
	cmd.Flags().StringVar(&bodyTipoDocumento, "tipo-documento", "", "Tipo documento")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
