// Copyright 2026 franklinbaldocausaganha. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newLoginPromotedCmd(flags *rootFlags) *cobra.Command {
	var bodyLogin string
	var bodySenha string

	cmd := &cobra.Command{
		Use:         "login",
		Short:       "Método de autenticação, para operações de inclusão e remoção de comunicações processuais. Método a ser...",
		Long:        "Shortcut for 'login create'. Método de autenticação, para operações de inclusão e remoção de comunicações processuais. Método a ser...",
		Example:     "  djen-pp-cli login --login example-value",
		Annotations: map[string]string{"pp:endpoint": "login.create", "pp:method": "POST", "pp:path": "/api/v1/login"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if !cmd.Flags().Changed("login") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "login")
			}
			if !cmd.Flags().Changed("senha") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "senha")
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/api/v1/login"
			// HasStore + non-GET falls through to a live API call here
			// rather than through resolveRead (GET-only internally); a
			// body-aware cached read helper is filed as #425 for when a
			// second store-backed POST-search consumer ships.
			body := map[string]any{}
			if bodyLogin != "" {
				body["login"] = bodyLogin
			}
			if bodySenha != "" {
				body["senha"] = bodySenha
			}
			data, _, err := c.Post(path, body)
			prov := attachFreshness(DataProvenance{Source: "live"}, flags)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Unwrap API response envelopes (e.g. {"status":"success","data":[...]})
			// so output helpers see the inner data, not the wrapper.
			data = extractResponseData(data)

			// Print provenance to stderr
			{
				var countItems []json.RawMessage
				if json.Unmarshal(data, &countItems) != nil {
					// Single object, not an array
					countItems = []json.RawMessage{data}
				}
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope. --select wins over
			// --compact when both are set; --compact only runs when no explicit
			// fields were requested. Explicit format flags (--csv, --quiet, --plain)
			// opt out of the auto-JSON path so piped consumers that asked for a
			// non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&bodyLogin, "login", "", "Login")
	cmd.Flags().StringVar(&bodySenha, "senha", "", "Senha")

	// Wire sibling endpoints and sub-resources as subcommands

	return cmd
}
