// Copyright 2026 franklinbaldocausaganha. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newCadernoPromotedCmd(flags *rootFlags) *cobra.Command {
	var flagData string
	var flagMeio string

	cmd := &cobra.Command{
		Use:         "caderno <sigla_tribunal>",
		Short:       "Método para download dos cadernos compactados de comunicações de cada tribunal.<br>O endpoint retorna metadados...",
		Long:        "Shortcut for 'caderno get'. Método para download dos cadernos compactados de comunicações de cada tribunal.<br>O endpoint retorna metadados...",
		Example:     "  djen-pp-cli caderno example-value --data 2026-01-15",
		Annotations: map[string]string{"pp:endpoint": "caderno.get", "pp:method": "GET", "pp:path": "/api/v1/caderno/{sigla_tribunal}/{data}/{meio}", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if !cmd.Flags().Changed("data") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "data")
			}
			if cmd.Flags().Changed("meio") {
				allowedMeio := []string{"E", "D"}
				validMeio := false
				for _, v := range allowedMeio {
					if flagMeio == v {
						validMeio = true
						break
					}
				}
				if !validMeio {
					fmt.Fprintf(os.Stderr, "warning: --%s %q not in allowed set %v\n", "meio", flagMeio, allowedMeio)
				}
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/api/v1/caderno/{sigla_tribunal}/{data}/{meio}"
			if len(args) < 1 {
				// JSON envelope: {error, usage}. Written first; the
				// usageErr return preserves exit code 2 across modes.
				if flags.asJSON {
					if printErr := printJSONFiltered(cmd.OutOrStdout(), map[string]any{
						"error": "sigla_tribunal is required",
						"usage": fmt.Sprintf("%s <%s>", cmd.CommandPath(), "sigla_tribunal"),
					}, flags); printErr != nil {
						return printErr
					}
				}
				return usageErr(fmt.Errorf("sigla_tribunal is required\nUsage: %s <%s>", cmd.CommandPath(), "sigla_tribunal"))
			}
			path = replacePathParam(path, "sigla_tribunal", args[0])
			path = replacePathParam(path, "data", fmt.Sprintf("%v", flagData))
			path = replacePathParam(path, "meio", fmt.Sprintf("%v", flagMeio))
			params := map[string]string{}
			data, prov, err := resolveRead(cmd.Context(), c, flags, "caderno", false, path, params, nil)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Unwrap API response envelopes (e.g. {"status":"success","data":[...]})
			// so output helpers see the inner data, not the wrapper.
			data = extractResponseData(data)

			// Print provenance to stderr
			{
				var countItems []json.RawMessage
				if json.Unmarshal(data, &countItems) != nil {
					// Single object, not an array
					countItems = []json.RawMessage{data}
				}
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope. --select wins over
			// --compact when both are set; --compact only runs when no explicit
			// fields were requested. Explicit format flags (--csv, --quiet, --plain)
			// opt out of the auto-JSON path so piped consumers that asked for a
			// non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagData, "data", "", "Data")
	cmd.Flags().StringVar(&flagMeio, "meio", "E", "'E' para Edital e 'D' para Diário Eletrônico (one of: E, D)")

	// Wire sibling endpoints and sub-resources as subcommands

	return cmd
}
