"""Regenerate the OKF-derived Pydantic domain models module (#1105).

`src/causaganha_mcp/_generated/domain_models.py` is generated from the
`knowledge/` TypeContract bundle. Field types come from the per-type declared
DuckDB schemas under `knowledge/.okf/specs/*.schema.sql`; examples are not a
second typing authority. The relational schema still supplies references and
projection composition.

Run after editing the bundle or its declared schemas:

    uv run python scripts/generate_okf_domain_models.py

The OKF CI gate regenerates and diffs the checked-in module, so stale bindings
fail before merge.
"""

from __future__ import annotations

from pathlib import Path

from okf_parser.schema_export import export_pydantic_source


_REPO_ROOT = Path(__file__).resolve().parents[1]
_KNOWLEDGE_ROOT = _REPO_ROOT / "knowledge"
_SPEC_TEMPLATE = ".okf/specs/{slug}.md"
_RELATIONAL_SCHEMA = "okf.schema.sql"
_OUTPUT_PATH = _REPO_ROOT / "src" / "causaganha_mcp" / "_generated" / "domain_models.py"

_BANNER = (
    "# GENERATED by scripts/generate_okf_domain_models.py — do not edit by hand.\n"
    "# Regenerate: uv run python scripts/generate_okf_domain_models.py\n"
)


def render() -> str:
    """Return the current generated module source, straight from `knowledge/`."""
    body = export_pydantic_source(
        str(_KNOWLEDGE_ROOT),
        spec_template=_SPEC_TEMPLATE,
        relational_schema=_RELATIONAL_SCHEMA,
    )
    return _BANNER + body


def main() -> None:
    _OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    _OUTPUT_PATH.write_text(render(), encoding="utf-8")


if __name__ == "__main__":
    main()
