"""Regenerate the OKF-derived Pydantic domain models module (#1105 slice 2).

`src/causaganha_mcp/_generated/domain_models.py` is a **generated** file — it
must never be edited by hand. It is produced by `okf_parser.schema_export`
straight from the `knowledge/` TypeContract bundle, so `ProcessoConsultarProjection`
and its nested concepts (`DjenResumoConcept`, `JurisDecisaoConcept`, ...) stay
mechanically derived from the same authority MCP and Web both read (RFC 0015).

Run after editing anything under `knowledge/`:

    uv run python scripts/generate_okf_domain_models.py

The OKF CI gate (`.github/workflows/okf.yml`) regenerates into a throwaway
file and diffs it against the checked-in one, failing the build on drift —
so a stale commit here is caught before merge, not discovered at runtime.

Deliberately does **not** pass `infer_types=True`: at okf-parser 0.45.6 that
flag infers `nr_processo`'s Python type from the bundle's example value
rather than trusting the relational schema's declared `VARCHAR`, producing
`nr_processo: int` — which would truncate any real CNJ with a leading zero
on validation. Every scalar field is `str` until that upstream inference bug
is fixed; see `tests/causaganha_mcp/test_okf_domain_models.py` for the
regression coverage this works around.
"""

from __future__ import annotations

from pathlib import Path

from okf_parser.schema_export import export_pydantic_source


_REPO_ROOT = Path(__file__).resolve().parents[1]
_KNOWLEDGE_ROOT = _REPO_ROOT / "knowledge"
_RELATIONAL_SCHEMA = "okf.schema.sql"
_OUTPUT_PATH = _REPO_ROOT / "src" / "causaganha_mcp" / "_generated" / "domain_models.py"

_BANNER = (
    "# GENERATED by scripts/generate_okf_domain_models.py — do not edit by hand.\n"
    "# Regenerate: uv run python scripts/generate_okf_domain_models.py\n"
)


def render() -> str:
    """Return the current generated module source, straight from `knowledge/`."""
    body = export_pydantic_source(str(_KNOWLEDGE_ROOT), relational_schema=_RELATIONAL_SCHEMA)
    return _BANNER + body


def main() -> None:
    _OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    _OUTPUT_PATH.write_text(render(), encoding="utf-8")


if __name__ == "__main__":
    main()
