"""Regenerate the OKF-derived Zod schemas module for the Web surface (#1105).

`web/src/lib/processoConsultar.gen.ts` is generated from the same `knowledge/`
TypeContract bundle that produces
`src/causaganha_mcp/_generated/domain_models.py` (see
`scripts/generate_okf_domain_models.py`). Both bindings come from one
authored contract, so MCP and Web validate the same `ProcessoConsultar`
projection instead of each declaring a second, hand-written description of
the same dossiê shape.

Run after editing the bundle or its declared schemas:

    uv run python scripts/generate_okf_zod_schemas.py

The OKF CI gate regenerates and diffs the checked-in module, so stale
bindings fail before merge.
"""

from __future__ import annotations

from pathlib import Path

from okf_parser.schema_export import export_zod_schema


_REPO_ROOT = Path(__file__).resolve().parents[1]
_KNOWLEDGE_ROOT = _REPO_ROOT / "knowledge"
_SPEC_TEMPLATE = ".okf/specs/{slug}.md"
_RELATIONAL_SCHEMA = "okf.schema.sql"
_OUTPUT_PATH = _REPO_ROOT / "web" / "src" / "lib" / "processoConsultar.gen.ts"

_BANNER = (
    "// GENERATED by scripts/generate_okf_zod_schemas.py — do not edit by hand.\n"
    "// Regenerate: uv run python scripts/generate_okf_zod_schemas.py\n"
)


def render() -> str:
    """Return the current generated module source, straight from `knowledge/`."""
    body = export_zod_schema(
        str(_KNOWLEDGE_ROOT),
        spec_template=_SPEC_TEMPLATE,
        relational_schema=_RELATIONAL_SCHEMA,
    )
    return _BANNER + body


def main() -> None:
    _OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    _OUTPUT_PATH.write_text(render(), encoding="utf-8")


if __name__ == "__main__":
    main()
