#!/usr/bin/env python3
"""Upload Parquet files to Internet Archive.

Uploads compressed embedding Parquet files to IA for long-term archival.
"""

import argparse
import os
import sys
from datetime import datetime
from pathlib import Path

import structlog


logger = structlog.get_logger()


def upload_to_internet_archive(
    file_path: Path, collection: str = "causaganha-embeddings"
) -> bool | None:
    """Upload file to Internet Archive.

    Args:
        file_path: Path to Parquet file to upload.
        collection: IA collection name.

    Note:
        Requires IA_ACCESS_KEY and IA_SECRET_KEY environment variables.
    """
    try:
        # Try to import internetarchive
        import internetarchive as ia
    except ImportError:
        logger.exception("internetarchive_not_installed")
        return False

    # Get credentials from environment
    access_key = os.getenv("IA_ACCESS_KEY")
    secret_key = os.getenv("IA_SECRET_KEY")

    if not access_key or not secret_key:
        logger.error("missing_ia_credentials")
        return False

    # Configure IA session
    session = ia.get_session(config={"s3": {"access": access_key, "secret": secret_key}})

    # Create item identifier (e.g., causaganha-embeddings-2026-01-21)
    date_str = datetime.utcnow().strftime("%Y-%m-%d")
    item_id = f"causaganha-embeddings-{date_str}"

    # Metadata
    metadata = {
        "collection": collection,
        "title": f"CausaGanha Embeddings - {date_str}",
        "description": (
            f"Judicial decision embeddings generated by CausaGanha on {date_str}. "
            "Contains vector embeddings of Brazilian legal decisions for similarity search."
        ),
        "mediatype": "data",
        "creator": "CausaGanha",
        "date": date_str,
        "subject": ["legal tech", "embeddings", "machine learning", "Brazil", "judiciary"],
        "language": "por",
    }

    logger.info(
        "uploading_to_ia",
        item_id=item_id,
        file=file_path.name,
        size_mb=round(file_path.stat().st_size / (1024 * 1024), 2),
    )

    try:
        # Upload file
        item = session.get_item(item_id)
        item.upload_file(
            str(file_path),
            metadata=metadata,
            access_key=access_key,
            secret_key=secret_key,
        )

        logger.info(
            "upload_completed",
            item_id=item_id,
            url=f"https://archive.org/details/{item_id}",
        )

    except Exception as e:
        logger.exception("upload_failed", error=str(e), error_type=type(e).__name__)
        return False
    else:
        return True


def main() -> int:
    """Upload Parquet file to Internet Archive."""
    parser = argparse.ArgumentParser(
        description="Upload embeddings to Internet Archive",
    )
    parser.add_argument(
        "--file",
        type=str,
        required=True,
        help="Parquet file to upload",
    )
    parser.add_argument(
        "--collection",
        type=str,
        default="causaganha-embeddings",
        help="IA collection name (default: causaganha-embeddings)",
    )

    args = parser.parse_args()

    file_path = Path(args.file)

    if not file_path.exists():
        logger.error("file_not_found", file=str(file_path))
        return 1

    # Skip upload if file is empty (no embeddings generated)
    if file_path.stat().st_size == 0:
        logger.info("skipping_empty_file", file=str(file_path))
        return 0

    # Upload
    success = upload_to_internet_archive(file_path, collection=args.collection)

    return 0 if success else 1


if __name__ == "__main__":
    sys.exit(main())
