// Copyright 2026 franklinbaldocausaganha. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package mcp

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"djen-pp-cli/internal/cli"
	"djen-pp-cli/internal/client"
	"djen-pp-cli/internal/cliutil"
	"djen-pp-cli/internal/config"
	"djen-pp-cli/internal/mcp/cobratree"
	"djen-pp-cli/internal/store"
	mcplib "github.com/mark3labs/mcp-go/mcp"
	"github.com/mark3labs/mcp-go/server"
)

// RegisterTools registers all API operations as MCP tools.
func RegisterTools(s *server.MCPServer) {
	s.AddTool(
		mcplib.NewTool("caderno_get",
			mcplib.WithDescription("Método para download dos cadernos compactados de comunicações de cada tribunal.<br>O endpoint retorna metadados sobre o caderno e URL temporária (5 minutos) para download.<br>Os cadernos do dia atual são disponibilizados a partir das 02:00. Required: sigla_tribunal, data, meio (default: E). Returns the CadernoGetResponse."),
			mcplib.WithString("sigla_tribunal", mcplib.Required(), mcplib.Description("Sigla tribunal")),
			mcplib.WithString("data", mcplib.Required(), mcplib.Description("Data")),
			mcplib.WithString("meio", mcplib.Description("'E' para Edital e 'D' para Diário Eletrônico")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/api/v1/caderno/{sigla_tribunal}/{data}/{meio}", []mcpParamBinding{{PublicName: "sigla_tribunal", WireName: "sigla_tribunal", Location: "path"}, {PublicName: "data", WireName: "data", Location: "path"}, {PublicName: "meio", WireName: "meio", Location: "path"}}, []string{"sigla_tribunal", "data", "meio"}),
	)
	s.AddTool(
		mcplib.NewTool("comunicacao_create",
			mcplib.WithDescription("Método de inserção de novas comunicações, a ser utilizado pelos Tribunais. Required: codigo_classe, data_disponibilizacao, destinatarios, meio, numero_processo, orgao, sigla_tribunal, tipo_comunicacao, tipo_documento. Optional: advogados, link, texto. Returns the new ComunicacaoCreateResponse."),
			mcplib.WithString("advogados", mcplib.Description("Advogados")),
			mcplib.WithString("codigo_classe", mcplib.Required(), mcplib.Description("Código da classe, conforme o SGT")),
			mcplib.WithString("data_disponibilizacao", mcplib.Required(), mcplib.Description("Data em que a comunicação será disponibilizada, no formato aaaa-mm-dd. Deverá ser maior que a data de hoje. Não...")),
			mcplib.WithString("destinatarios", mcplib.Required(), mcplib.Description("Destinatarios")),
			mcplib.WithString("link", mcplib.Description("Link para o inteiro teor da comunicação")),
			mcplib.WithString("meio", mcplib.Required(), mcplib.Description("'E' para Edital e 'D' para Diário Eletrônico")),
			mcplib.WithString("numero_processo", mcplib.Required(), mcplib.Description("Número do processo, conforme a numeração única do CNJ. Somente números.")),
			mcplib.WithString("orgao", mcplib.Required(), mcplib.Description("Órgão gerador da comunicação")),
			mcplib.WithString("sigla_tribunal", mcplib.Required(), mcplib.Description("Sigla tribunal")),
			mcplib.WithString("texto", mcplib.Description("Teor da comunicação")),
			mcplib.WithString("tipo_comunicacao", mcplib.Required(), mcplib.Description("'C' para Citação, 'E' para Edital, 'I' para Intimação, 'P' para Pauta de julgamento, 'L' para Lista de...")),
			mcplib.WithString("tipo_documento", mcplib.Required(), mcplib.Description("Tipo documento")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/api/v1/comunicacao", []mcpParamBinding{{PublicName: "advogados", WireName: "advogados", Location: "body"}, {PublicName: "codigo_classe", WireName: "codigo_classe", Location: "body"}, {PublicName: "data_disponibilizacao", WireName: "data_disponibilizacao", Location: "body"}, {PublicName: "destinatarios", WireName: "destinatarios", Location: "body"}, {PublicName: "link", WireName: "link", Location: "body"}, {PublicName: "meio", WireName: "meio", Location: "body"}, {PublicName: "numero_processo", WireName: "numero_processo", Location: "body"}, {PublicName: "orgao", WireName: "orgao", Location: "body"}, {PublicName: "sigla_tribunal", WireName: "sigla_tribunal", Location: "body"}, {PublicName: "texto", WireName: "texto", Location: "body"}, {PublicName: "tipo_comunicacao", WireName: "tipo_comunicacao", Location: "body"}, {PublicName: "tipo_documento", WireName: "tipo_documento", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("comunicacao_delete",
			mcplib.WithDescription("Cancela comunicações. Caso a comunicação não tenha sido disponibilizada, não aparecerá em qualquer forma nas consultas. Caso a comunicação já tenha sido disponibilizada, o conteúdo será substituído pelo motivo de cancelamento. Pode levar algumas horas para refletir em todas as pesquisas do sistema. Required: id, motivo_cancelamento. Returns the ComunicacaoDeleteResponse. Destructive."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("Id")),
			mcplib.WithString("motivo_cancelamento", mcplib.Required(), mcplib.Description("Motivo cancelamento")),
			mcplib.WithDestructiveHintAnnotation(true),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("DELETE", "/api/v1/comunicacao/{id}", []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"}, {PublicName: "motivo_cancelamento", WireName: "motivo_cancelamento", Location: "body"}}, []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("comunicacao_list",
			mcplib.WithDescription("Método de consulta de comunicações.<br><br><b>Atenção: as seguintes consultas são limitadas em 10000 resultados:</b><br>- pesquisas com campos textuais ou OAB (texto, nome de advogado, OAB e nome de parte)<br>- pesquisas com 5 ou menos itensPorPagina<br>- pesquisas com data de início e data de fim diferentes<br>- pesquisas com número de processo.<br><br>A pesquisa deve conter pelo menos um dos seguintes parâmetros: siglaTribunal, texto, nomeParte, nomeAdvogado, numeroOab, numeroProcesso ou ser limitada a 5 itensPorPagina.<br><br>As consultas estão sujeitas a controle de taxa de requisições por IP que pode ser controlado com os seguintes cabeçalhos retornados:<br>- x-ratelimit-limit: janela de quantidade de requisições<br>- x-ratelimit-remaining: quantidade de requisições restantes na atual janela.<br>Ao receber um erro 429 orienta-se aguardar 1 minuto para retomar as requisições para evitar um loop de erros.<br>A utilização de múltiplos IPs por um mesmo cliente para contornar o controle da taxa de requisições é considerado uso abusivo e poderá resultar em bloqueios. Optional: numeroOab, ufOab, nomeAdvogado (plus 10 more). Returns the ComunicacaoListResponse."),
			mcplib.WithString("numeroOab", mcplib.Description("Numero oab")),
			mcplib.WithString("ufOab", mcplib.Description("Uf oab")),
			mcplib.WithString("nomeAdvogado", mcplib.Description("Nome advogado")),
			mcplib.WithString("nomeParte", mcplib.Description("Nome parte")),
			mcplib.WithString("numeroProcesso", mcplib.Description("Numero processo")),
			mcplib.WithString("dataDisponibilizacaoInicio", mcplib.Description("Data inicial de disponibilização da comunicação no diário, no formato yyyy-mm-dd")),
			mcplib.WithString("dataDisponibilizacaoFim", mcplib.Description("Data fim de disponibilização da comunicação no diário, no formato yyyy-mm-dd")),
			mcplib.WithString("siglaTribunal", mcplib.Description("Sigla do Tribunal para filtrar as comunicações")),
			mcplib.WithString("numeroComunicacao", mcplib.Description("Número de identificação da comunicação")),
			mcplib.WithString("pagina", mcplib.Description("Número da página")),
			mcplib.WithString("itensPorPagina", mcplib.Description("Número de itens por página para paginação (valores válidos: 5 e 100)")),
			mcplib.WithString("orgaoId", mcplib.Description("Identificador interno do órgão requisitante")),
			mcplib.WithString("meio", mcplib.Description("'E' para Edital e 'D' para Diário Eletrônico")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/api/v1/comunicacao", []mcpParamBinding{{PublicName: "numeroOab", WireName: "numeroOab", Location: "query"}, {PublicName: "ufOab", WireName: "ufOab", Location: "query"}, {PublicName: "nomeAdvogado", WireName: "nomeAdvogado", Location: "query"}, {PublicName: "nomeParte", WireName: "nomeParte", Location: "query"}, {PublicName: "numeroProcesso", WireName: "numeroProcesso", Location: "query"}, {PublicName: "dataDisponibilizacaoInicio", WireName: "dataDisponibilizacaoInicio", Location: "query"}, {PublicName: "dataDisponibilizacaoFim", WireName: "dataDisponibilizacaoFim", Location: "query"}, {PublicName: "siglaTribunal", WireName: "siglaTribunal", Location: "query"}, {PublicName: "numeroComunicacao", WireName: "numeroComunicacao", Location: "query"}, {PublicName: "pagina", WireName: "pagina", Location: "query"}, {PublicName: "itensPorPagina", WireName: "itensPorPagina", Location: "query"}, {PublicName: "orgaoId", WireName: "orgaoId", Location: "query"}, {PublicName: "meio", WireName: "meio", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("comunicacao_list-tribunal",
			mcplib.WithDescription("Este endpoint retorna lista de tribunais por UF de atuação com as datas de último envio disponibilizado pelo tribunal. Returns array of ComunicacaoListTribunalItem."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/api/v1/comunicacao/tribunal", []mcpParamBinding{}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("comunicacao_certidao_get",
			mcplib.WithDescription("GET /api/v1/comunicacao/{hash}/certidao. Required: hash."),
			mcplib.WithString("hash", mcplib.Required(), mcplib.Description("Hash")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/api/v1/comunicacao/{hash}/certidao", []mcpParamBinding{{PublicName: "hash", WireName: "hash", Location: "path"}}, []string{"hash"}),
	)
	s.AddTool(
		mcplib.NewTool("login_create",
			mcplib.WithDescription("Método de autenticação, para operações de inclusão e remoção de comunicações processuais. Método a ser utilizado pelos Tribunais. Required: login, senha. Returns the new LoginCreateResponse."),
			mcplib.WithString("login", mcplib.Required(), mcplib.Description("Login")),
			mcplib.WithString("senha", mcplib.Required(), mcplib.Description("Senha")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/api/v1/login", []mcpParamBinding{{PublicName: "login", WireName: "login", Location: "body"}, {PublicName: "senha", WireName: "senha", Location: "body"}}, []string{}),
	)
	// SQL tool — ad-hoc analysis on synced data without API calls
	s.AddTool(
		mcplib.NewTool("sql",
			mcplib.WithDescription("Run read-only SQL against local database. Use for ad-hoc analysis, aggregations, and joins across synced resources. Requires sync first."),
			mcplib.WithString("query", mcplib.Required(), mcplib.Description("SQL query (SELECT or WITH...SELECT). Tables match resource names.")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
		),
		handleSQL,
	)

	// Context tool — front-loaded domain knowledge for agents.
	// Call this first to understand the API taxonomy, query patterns, and capabilities.
	s.AddTool(
		mcplib.NewTool("context",
			mcplib.WithDescription("Get API domain context: resource taxonomy, auth requirements, query tips, and unique capabilities. Call this first."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
		),
		handleContext,
	)

	// Runtime Cobra-tree mirror — exposes every user-facing command that is
	// not already covered by a typed endpoint or framework MCP tool.
	cobratree.RegisterAll(s, cli.RootCmd(), cobratree.SiblingCLIPath)
}

type mcpParamBinding struct {
	PublicName string
	WireName   string
	Location   string
}

// makeAPIHandler creates a generic MCP tool handler for an API endpoint.
func makeAPIHandler(method, pathTemplate string, bindings []mcpParamBinding, positionalParams []string) server.ToolHandlerFunc {
	return func(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
		c, err := newMCPClient()
		if err != nil {
			return mcplib.NewToolResultError(err.Error()), nil
		}

		// mcp-go v0.47+ made CallToolParams.Arguments an `any` to support
		// non-map payloads; GetArguments() returns the map[string]any shape
		// we rely on here (or an empty map when the payload is something else).
		args := req.GetArguments()

		// positionalParams mixes real URL path params with CLI positional
		// args that map to query params (e.g. `search <query>` -> ?query=);
		// the placeholder check below disambiguates them at runtime.
		path := pathTemplate
		knownArgs := make(map[string]bool, len(bindings))
		pathParams := make(map[string]bool, len(positionalParams))
		params := make(map[string]string)
		bodyArgs := make(map[string]any)
		for _, binding := range bindings {
			knownArgs[binding.PublicName] = true
			v, ok := args[binding.PublicName]
			if !ok {
				continue
			}
			switch binding.Location {
			case "path":
				placeholder := "{" + binding.WireName + "}"
				pathParams[binding.PublicName] = true
				path = strings.Replace(path, placeholder, fmt.Sprintf("%v", v), 1)
			case "body":
				bodyArgs[binding.WireName] = v
			default:
				params[binding.WireName] = fmt.Sprintf("%v", v)
			}
		}
		for _, p := range positionalParams {
			placeholder := "{" + p + "}"
			if !strings.Contains(pathTemplate, placeholder) {
				continue
			}
			pathParams[p] = true
			if v, ok := args[p]; ok {
				path = strings.Replace(path, placeholder, fmt.Sprintf("%v", v), 1)
			}
		}

		for k, v := range args {
			if pathParams[k] || knownArgs[k] {
				continue
			}
			switch method {
			case "POST", "PUT", "PATCH":
				bodyArgs[k] = v
			default:
				params[k] = fmt.Sprintf("%v", v)
			}
		}

		var data json.RawMessage
		switch method {
		case "GET":
			data, err = c.Get(path, params)
		case "POST":
			body, _ := json.Marshal(bodyArgs)
			data, _, err = c.Post(path, body)
		case "PUT":
			body, _ := json.Marshal(bodyArgs)
			data, _, err = c.Put(path, body)
		case "PATCH":
			body, _ := json.Marshal(bodyArgs)
			data, _, err = c.Patch(path, body)
		case "DELETE":
			data, _, err = c.Delete(path)
		default:
			return mcplib.NewToolResultError("unsupported method: " + method), nil
		}

		if err != nil {
			msg := err.Error()
			switch {
			case strings.Contains(msg, "HTTP 409"):
				return mcplib.NewToolResultText("already exists (no-op)"), nil
			case strings.Contains(msg, "HTTP 400") && cliutil.LooksLikeAuthError(msg):
				return mcplib.NewToolResultError("authentication error: " + cliutil.SanitizeErrorBody(msg) +
					"\nhint: the API rejected the request — this usually means auth is missing or invalid." +
					"\n      Set your API key: export DIARIO_DE_JUSTICA_BEARER=<your-key>" +
					"\n      Run 'djen-pp-cli doctor' to check auth status."), nil
			case strings.Contains(msg, "HTTP 401"):
				return mcplib.NewToolResultError("authentication failed: " + cliutil.SanitizeErrorBody(msg) +
					"\nhint: check your API key." +
					"\n      Set it with: export DIARIO_DE_JUSTICA_BEARER=<your-key>" +
					"\n      Run 'djen-pp-cli doctor' to check auth status."), nil
			case strings.Contains(msg, "HTTP 403"):
				return mcplib.NewToolResultError("permission denied: " + cliutil.SanitizeErrorBody(msg) +
					"\nhint: your credentials are valid but lack access to this resource." +
					"\n      Set it with: export DIARIO_DE_JUSTICA_BEARER=<your-key>" +
					"\n      Run 'djen-pp-cli doctor' to check auth status."), nil
			case strings.Contains(msg, "HTTP 404"):
				if method == "DELETE" {
					return mcplib.NewToolResultText("already deleted (no-op)"), nil
				}
				return mcplib.NewToolResultError("not found: " + msg), nil
			case strings.Contains(msg, "HTTP 429"):
				return mcplib.NewToolResultError("rate limited: " + msg), nil
			default:
				return mcplib.NewToolResultError(msg), nil
			}
		}

		// For GET responses, wrap bare arrays with count metadata
		if method == "GET" {
			trimmed := strings.TrimSpace(string(data))
			if len(trimmed) > 0 && trimmed[0] == '[' {
				var items []json.RawMessage
				if json.Unmarshal(data, &items) == nil {
					wrapped := map[string]any{
						"count": len(items),
						"items": items,
					}
					out, _ := json.Marshal(wrapped)
					return mcplib.NewToolResultText(string(out)), nil
				}
			}
		}
		return mcplib.NewToolResultText(string(data)), nil
	}
}

func newMCPClient() (*client.Client, error) {
	home, _ := os.UserHomeDir()
	cfgPath := filepath.Join(home, ".config", "djen-pp-cli", "config.toml")
	cfg, err := config.Load(cfgPath)
	if err != nil {
		return nil, fmt.Errorf("loading config: %w", err)
	}
	c := client.New(cfg, 30*time.Second, 0)
	// Agents calling through MCP need fresh data every call. The on-disk
	// response cache survives across MCP server invocations, so a
	// DELETE/PATCH followed by a GET would otherwise return the
	// pre-mutation snapshot for up to the cache TTL. The interactive CLI
	// constructs its own client and is unaffected.
	c.NoCache = true
	return c, nil
}

func dbPath() string {
	home, _ := os.UserHomeDir()
	return filepath.Join(home, ".local", "share", "djen-pp-cli", "data.db")
}

// Note: MCP tools use their own dbPath() because they are in a separate package (main, not cli).
// The CLI's defaultDBPath() in the cli package uses the same canonical path.

// validateReadOnlyQuery gates the MCP sql tool. The agent contract advertised
// to the host is ReadOnlyHintAnnotation(true); a false annotation on a
// mutating tool lets MCP hosts auto-approve writes and is treated as a real
// bug per the project's agent-native security model.
//
// The gate is an allowlist (SELECT or WITH only) applied AFTER stripping the
// leading whitespace, line comments, block comments, and semicolons that
// SQLite itself ignores before parsing. A naive HasPrefix check on a
// keyword blocklist is bypassable by prefixing the dangerous statement with
// "/* x */" or "-- x\n" — TrimSpace strips outer whitespace but does not
// understand SQL comment syntax. Combined with the empirical fact that
// modernc.org/sqlite's mode=ro does NOT block VACUUM INTO (writes a snapshot
// to a new file) or ATTACH DATABASE (opens a separate writable handle),
// such a bypass produces silent exfiltration to an attacker-chosen path.
//
// SELECT and WITH are the only allowed leading keywords. WITH supports
// SELECT-form CTEs; CTE-wrapped writes ("WITH x AS (...) INSERT ...") are
// caught by OpenReadOnly's mode=ro one layer down. PRAGMA, ATTACH, VACUUM,
// and every other DDL/DML keyword fail at this gate before reaching SQLite.
func validateReadOnlyQuery(query string) error {
	upper := strings.ToUpper(stripLeadingSQLNoise(query))
	if !strings.HasPrefix(upper, "SELECT") && !strings.HasPrefix(upper, "WITH") {
		return fmt.Errorf("only SELECT queries are allowed")
	}
	return nil
}

// stripLeadingSQLNoise removes leading whitespace, SQL line comments
// (-- to end of line), block comments (/* ... */), and statement
// separators (;) from query. SQLite skips these before parsing the first
// keyword, so a security gate that does not strip them mismatches what the
// driver actually executes.
func stripLeadingSQLNoise(query string) string {
	for {
		query = strings.TrimLeft(query, " \t\r\n;")
		switch {
		case strings.HasPrefix(query, "--"):
			if idx := strings.IndexByte(query, '\n'); idx >= 0 {
				query = query[idx+1:]
				continue
			}
			return ""
		case strings.HasPrefix(query, "/*"):
			if idx := strings.Index(query[2:], "*/"); idx >= 0 {
				query = query[2+idx+2:]
				continue
			}
			return ""
		default:
			return query
		}
	}
}

func handleSQL(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	args := req.GetArguments()
	query, ok := args["query"].(string)
	if !ok || query == "" {
		return mcplib.NewToolResultError("query is required"), nil
	}

	if err := validateReadOnlyQuery(query); err != nil {
		return mcplib.NewToolResultError(err.Error()), nil
	}

	db, err := store.OpenReadOnly(dbPath())
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("opening database: %v", err)), nil
	}
	defer db.Close()

	rows, err := db.Query(query)
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("query failed: %v", err)), nil
	}
	defer rows.Close()

	cols, _ := rows.Columns()
	var results []map[string]any
	for rows.Next() {
		values := make([]any, len(cols))
		ptrs := make([]any, len(cols))
		for i := range values {
			ptrs[i] = &values[i]
		}
		rows.Scan(ptrs...)
		row := make(map[string]any)
		for i, col := range cols {
			row[col] = values[i]
		}
		results = append(results, row)
	}

	data, _ := json.MarshalIndent(results, "", "  ")
	return mcplib.NewToolResultText(string(data)), nil
}

func handleContext(_ context.Context, _ mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	ctx := map[string]any{
		"api":         "djen",
		"description": "Última atualização em 29/05/2025.<br>- Atualizado informações sobre parâmetros do endpoint GET...",
		"archetype":   "generic",
		"tool_count":  7,
		// tool_surface tells agents which surface a capability lives on.
		"tool_surface": "MCP exposes typed endpoint tools plus a runtime mirror of user-facing CLI commands. Endpoint tools keep typed schemas; command-mirror tools shell out to the companion djen-pp-cli binary.",
		"auth": map[string]any{
			"type": "api_key",
			"env_vars": []map[string]any{
				{
					"name":        "DIARIO_DE_JUSTICA_BEARER",
					"kind":        "per_call",
					"required":    true,
					"sensitive":   true,
					"description": "Set to your API credential.",
				},
			},
		},
		"resources": []map[string]any{
			{
				"name":        "caderno",
				"description": "Manage caderno",
				"endpoints":   []string{"get"},
				"searchable":  true,
			},
			{
				"name":        "comunicacao",
				"description": "Manage comunicacao",
				"endpoints":   []string{"create", "delete", "list", "list-tribunal"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "login",
				"description": "Manage login",
				"endpoints":   []string{"create"},
				"searchable":  true,
			},
		},
		"query_tips": []string{
			"Pagination uses cursor-based paging. Pass after parameter for subsequent pages.",
			"Control page size with the limit parameter (default 100).",
			"Use the sql tool for ad-hoc analysis on synced data. Run sync first to populate the local database.",
			"Use the search tool for full-text search across all synced resources. Faster than iterating list endpoints.",
			"Prefer sql/search over repeated API calls when the data is already synced.",
		},
	}
	data, _ := json.MarshalIndent(ctx, "", "  ")
	return mcplib.NewToolResultText(string(data)), nil
}

// RegisterNovelFeatureTools is kept as a compatibility no-op for older MCP
// mains. New generated mains call RegisterTools only; RegisterTools now
// includes the runtime Cobra-tree mirror.
func RegisterNovelFeatureTools(s *server.MCPServer) {
	_ = s
}
