// Copyright 2026 franklinbaldocausaganha. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package types

import "encoding/json"

type CadernoGetResponse struct {
	Data              string  `json:"data"`
	Hash              string  `json:"hash"`
	Meio              string  `json:"meio"`
	NumeroPaginas     float64 `json:"numero_paginas"`
	SiglaTribunal     string  `json:"sigla_tribunal"`
	Status            string  `json:"status"`
	TotalComunicacoes float64 `json:"total_comunicacoes"`
	Tribunal          string  `json:"tribunal"`
	Url               string  `json:"url"`
	Versao            string  `json:"versao"`
}

type ComunicacaoCreateResponse struct {
	Items   json.RawMessage `json:"items"`
	Message string          `json:"message"`
	Status  string          `json:"status"`
}

type ComunicacaoDeleteResponse struct {
	Message string `json:"message"`
	Status  string `json:"status"`
}

type ComunicacaoListResponse struct {
	Count   float64         `json:"count"`
	Items   json.RawMessage `json:"items"`
	Message string          `json:"message"`
	Status  string          `json:"status"`
}

type ComunicacaoListTribunalItem struct {
	Endereco   string `json:"endereco"`
	Id         int    `json:"id"`
	Jurisdicao string `json:"jurisdicao"`
	Nome       string `json:"nome"`
	Sigla      string `json:"sigla"`
	Telefone   string `json:"telefone"`
}

type LoginCreateResponse struct {
	AccessToken string          `json:"access_token"`
	User        json.RawMessage `json:"user"`
}
